(()=>{
const KEY='money_journal_v2_state',THEME='mj_theme_mode';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>(+n||0).toLocaleString('vi-VN');
const norm=x=>x==='money_in'?'moneyin':x==='debt_payment'?'debt':x;
const TYPES=[['spending','Chi'],['income','Thu'],['moneyin','Tiền nhận'],['debt','Trả thẻ'],['refund','Hoàn tiền'],['transfer','Chuyển tiền']];
const CATS=['Ăn uống','Mua sắm','Di chuyển','Hóa đơn','Hẹn hò','Giải trí','Sức khỏe','Làm đẹp','Dịch vụ số','Quà tặng','Phí','Trả góp','Thanh toán dư nợ','Tiết kiệm','Lương','Khác'];
const SOURCES=['Tiền mặt','VPBank','Shinhan','Ví Trả Sau','Tài khoản ngân hàng','Tiết kiệm','Khác'];
let page='home',month=null,flowFilter='all',query='',editing=null,attachment=null,draft={};
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');s.transactions=Array.isArray(s.transactions)?s.transactions:[];s.accounts=Array.isArray(s.accounts)?s.accounts:[];s.budgets=Array.isArray(s.budgets)?s.budgets:[];return s}catch{return{transactions:[],accounts:[],budgets:[]}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function months(){return[...new Set(load().transactions.map(t=>String(t.date||'').slice(0,7)).filter(x=>/^\d{4}-\d{2}$/.test(x)))].sort().reverse()}
function activeMonth(){const ms=months();return month&&ms.includes(month)?month:(ms[0]||new Date().toISOString().slice(0,7))}
function ml(ym){if(!ym)return'';const[y,m]=ym.split('-');return`Tháng ${+m}/${y}`}
function typeOf(t){return norm(String(t.type||''))}
function icon(name){const p={home:'<path d="M3 11.5 12 4l9 7.5V20a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',flow:'<path d="M4 7h10M10 3l4 4-4 4M20 17H10m4-4-4 4 4 4"/>',plan:'<path d="M4 19V9m6 10V5m6 14v-7m4 7H2"/>',settings:'<path d="M12 15.5A3.5 3.5 0 1 0 12 8a3.5 3.5 0 0 0 0 7.5Zm8-3.5 2-1-2-4-2 .5a8 8 0 0 0-2-1.2L15.5 4h-7L8 6.3A8 8 0 0 0 6 7.5L4 7 2 11l2 1-.1 1 .1 1-2 1 2 4 2-.5a8 8 0 0 0 2 1.2l.5 2.3h7l.5-2.3a8 8 0 0 0 2-1.2l2 .5 2-4-2-1 .1-1Z"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',filter:'<path d="M4 6h16M7 12h10M10 18h4"/>',wallet:'<path d="M4 7h15a2 2 0 0 1 2 2v9H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h13v3"/><path d="M16 11h5v4h-5a2 2 0 0 1 0-4Z"/>',bank:'<path d="m3 9 9-5 9 5M5 10v8m4-8v8m6-8v8m4-8v8M3 20h18"/>',food:'<path d="M7 3v8M4 3v5a3 3 0 0 0 6 0V3M16 3v18M16 3c3 0 4 3 4 6s-1 5-4 5"/>',shop:'<path d="M6 8h12l1 13H5L6 8Zm3 0V6a3 3 0 0 1 6 0v2"/>',car:'<path d="m5 11 2-5h10l2 5M4 11h16v7H4zM7 18v2m10-2v2"/>',bill:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2zM9 8h6M9 12h6"/>',calendar:'<path d="M5 4v3m14-3v3M3 9h18M4 6h16v15H4z"/>',note:'<path d="M5 4h14v16H5zM8 9h8M8 13h6"/>',camera:'<path d="M4 7h4l2-3h4l2 3h4v12H4z"/><circle cx="12" cy="13" r="4"/>',file:'<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5"/>',moon:'<path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5Z"/>',cloud:'<path d="M6 18h11a4 4 0 0 0 .6-8A6 6 0 0 0 6.4 8.5 4.8 4.8 0 0 0 6 18Z"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M5 21h14"/>',upload:'<path d="M12 15V3m-4 4 4-4 4 4M5 21h14"/>',trash:'<path d="M4 7h16M9 7V4h6v3m-8 0 1 14h8l1-14"/>',bell:'<path d="M6 9a6 6 0 0 1 12 0v5l2 3H4l2-3zM10 20h4"/>',plus:'<path d="M12 5v14M5 12h14"/>',back:'<path d="m15 18-6-6 6-6"/>'}[name]||'<circle cx="12" cy="12" r="8"/>';
return`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p}</svg>`}
function calc(){const s=load(),ym=activeMonth(),rows=s.transactions.filter(t=>String(t.date||'').startsWith(ym));const sum=t=>rows.filter(x=>typeOf(x)===t).reduce((a,b)=>a+(+b.amount||0),0),income=sum('income'),moneyin=sum('moneyin'),spend=sum('spending'),debt=sum('debt'),refund=sum('refund'),left=income+moneyin-spend-debt+refund;const bal=n=>s.accounts.find(a=>String(a.name||'').toLowerCase()===n.toLowerCase())?.balance||0;return{s,ym,rows,income,moneyin,spend,debt,refund,left,cash:bal('Tiền mặt'),savings:bal('Tiết kiệm')}}
function catStats(rows){const m=new Map();rows.filter(t=>typeOf(t)==='spending').forEach(t=>m.set(t.category||'Khác',(m.get(t.category||'Khác')||0)+(+t.amount||0)));const r=[...m].map(([category,amount])=>({category,amount})).sort((a,b)=>b.amount-a.amount);return{r,total:r.reduce((a,b)=>a+b.amount,0),max:r[0]?.amount||1}}
function catColor(i){return['var(--orange)','#f47b72','var(--violet)','var(--cyan)','#83d39c','var(--blue)'][i%6]}
function txIcon(t){const c=t.category||'';if(/ăn/i.test(c))return['food','#fff0df','#bb6d18'];if(/mua/i.test(c))return['shop','#efeaff','#6d58c9'];if(/di chuyển/i.test(c))return['car','#def5ec','#208162'];if(/hóa đơn/i.test(c))return['bill','#e6eefc','#4666b1'];if(typeOf(t)==='income'||typeOf(t)==='moneyin')return['wallet','#def5ec','#208162'];return['note','#f3eee4','#80683f']}
function txRows(list){const a=[...list].sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));return a.map(t=>{const[i,bg,cl]=txIcon(t),date=String(t.date||'').split('-').reverse().join('/'),sign=(typeOf(t)==='income'||typeOf(t)==='moneyin'||typeOf(t)==='refund')?'+':'-';return`<button class="tx" data-edit="${esc(t.id)}"><span class="tx-icon" style="background:${bg};color:${cl}">${icon(i)}</span><span class="tx-main"><b>${esc(t.note||t.name||t.category||'Giao dịch')}</b><small>${esc(t.category||'Khác')} · ${esc(t.source||t.account||'')}</small></span><span class="tx-right"><b style="color:${sign==='+'?'var(--green)':'var(--ink)'}">${sign}${fmt(t.amount)}đ</b><small>${date}</small></span></button>`}).join('')||'<div class="empty">Chưa có giao dịch.</div>'}
function upcoming(c){const today=new Date().toISOString().slice(0,10);const due=(c.s.transactions||[]).filter(t=>t.due_date&&t.due_date>=today).sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date))).slice(0,3);if(due.length)return due.map(t=>`<div class="up-row"><span class="tx-icon">${icon('calendar')}</span><span><b>${esc(t.note||t.name||'Khoản sắp tới')}</b><small>${String(t.due_date).split('-').reverse().join('/')}</small></span><strong>${fmt(t.amount)}đ</strong></div>`).join('');const b=(c.s.budgets||[]).map(x=>{const spent=c.rows.filter(t=>typeOf(t)==='spending'&&(t.category||'Khác')===x.name).reduce((s,t)=>s+(+t.amount||0),0);return{name:x.name,spent,limit:+x.limit||0,p:x.limit?Math.round(spent/x.limit*100):0}}).filter(x=>x.p>=75).sort((a,b)=>b.p-a.p).slice(0,3);if(b.length)return b.map(x=>`<div class="up-row"><span class="tx-icon">${icon('plan')}</span><span><b>${esc(x.name)}</b><small>Đã dùng ${x.p}% ngân sách</small></span><strong>${fmt(Math.max(0,x.limit-x.spent))}đ</strong></div>`).join('');return'<div class="empty">Chưa có khoản nào cần chú ý.</div>'}
function home(){const c=calc(),st=catStats(c.rows),top=st.r.slice(0,5);return`<section class="hero"><div class="hero-label">Tiền còn lại · ${ml(c.ym)}</div><div class="hero-amount">${fmt(c.left)}đ</div><div class="hero-delta">● Theo dõi tháng hiện tại</div><div class="hero-grid"><div class="hero-stat"><small>Thu nhập</small><b>${fmt(c.income)}đ</b></div><div class="hero-stat"><small>Chi tiêu</small><b>${fmt(c.spend)}đ</b></div><div class="hero-stat"><small>Trả thẻ</small><b>${fmt(c.debt)}đ</b></div></div></section><div class="section-head"><h2>Tài sản</h2><button data-page="settings">Chỉnh số dư ›</button></div><div class="asset-grid"><div class="asset-card"><span class="asset-icon">${icon('wallet')}</span><small>Tiền mặt</small><b>${fmt(c.cash)}đ</b></div><div class="asset-card"><span class="asset-icon blue">${icon('bank')}</span><small>Tiết kiệm</small><b>${fmt(c.savings)}đ</b></div></div><div class="section-head"><h2>Chi tiêu theo danh mục</h2><span>Tháng này</span></div><div class="panel category-panel"><div class="cat-wrap"><div class="donut"><div class="donut-center"><small>Tổng chi</small><b>${fmt(st.total)}đ</b></div></div><div class="legend">${top.map((x,i)=>`<div class="legend-row"><i class="legend-dot" style="background:${catColor(i)}"></i><b>${esc(x.category)}</b><span>${st.total?Math.round(x.amount/st.total*100):0}%</span></div>`).join('')||'<div class="empty">Chưa có chi tiêu</div>'}</div></div></div><div class="section-head"><h2>Sắp tới</h2></div><div class="panel upcoming">${upcoming(c)}</div>`}
function flow(){const c=calc(),ms=months(),idx=Math.max(0,ms.indexOf(c.ym));let list=c.rows;if(flowFilter==='income')list=list.filter(t=>['income','moneyin','refund'].includes(typeOf(t)));if(flowFilter==='out')list=list.filter(t=>['spending','debt'].includes(typeOf(t)));if(query)list=list.filter(t=>`${t.note||t.name||''} ${t.category||''} ${t.source||t.account||''}`.toLowerCase().includes(query.toLowerCase()));const incoming=c.income+c.moneyin+c.refund,out=c.spend+c.debt,total=incoming+out,ip=total?Math.round(incoming/total*100):50;return`<div class="page-head"><h1>Dòng tiền</h1><div class="actions"><button class="icon-btn" id="focusSearch">${icon('search')}</button><button class="icon-btn">${icon('filter')}</button></div></div><div class="seg"><button class="${flowFilter==='all'?'active':''}" data-filter="all">Tất cả</button><button class="${flowFilter==='income'?'active':''}" data-filter="income">Thu</button><button class="${flowFilter==='out'?'active':''}" data-filter="out">Chi</button></div><div class="search-wrap">${icon('search')}<input id="search" class="search" value="${esc(query)}" placeholder="Tìm giao dịch, danh mục..."></div><div class="panel summary-card"><div class="summary-title">Tổng quan ${ml(c.ym).toLowerCase()}</div><div class="summary-grid"><div class="income"><small>Thu</small><b>${fmt(incoming)}đ</b></div><div class="out"><small>Chi + trả thẻ</small><b>-${fmt(out)}đ</b></div></div><div class="flow-bar"><i style="width:${ip}%"></i><i style="width:${100-ip}%"></i></div></div><div class="section-head"><h2>${ml(c.ym)}</h2><span>${list.length} giao dịch</span></div><div class="panel tx-list">${txRows(list)}</div><div class="section-head"><h2>Chọn tháng</h2><div><button data-month="${ms[idx+1]||''}" ${ms[idx+1]?'':'disabled'}>‹</button><button data-month="${ms[idx-1]||''}" ${ms[idx-1]?'':'disabled'}>›</button></div></div>`}
function initDraft(t){const src=t||{};draft={type:norm(src.type)||'spending',amount:src.amount||'',date:src.date||new Date().toISOString().slice(0,10),category:src.category||'Ăn uống',source:src.source||src.account||'Tiền mặt',note:src.note||src.name||''};attachment=null}
function add(){const spending=draft.type==='spending',topCats=['Ăn uống','Mua sắm','Di chuyển','Hóa đơn','Khác'];return`<div class="add-screen"><div class="add-title"><button class="icon-btn" id="backAdd">${icon('back')}</button><h1>${editing?'Sửa giao dịch':'Nhập giao dịch'}</h1><span style="width:38px"></span></div><div class="type-toggle"><button class="${!['income','moneyin'].includes(draft.type)?'active':''}" data-type="spending">Chi</button><button class="${['income','moneyin'].includes(draft.type)?'active':''}" data-type="income">Thu</button></div><div class="cat-scroller">${topCats.map(c=>{const nm=c==='Ăn uống'?'food':c==='Mua sắm'?'shop':c==='Di chuyển'?'car':c==='Hóa đơn'?'bill':'note';return`<button class="cat-choice ${draft.category===c?'active':''}" data-cat="${c}"><span class="cat-icon">${icon(nm)}</span><span>${c}</span></button>`}).join('')}</div><div class="field"><label>Số tiền</label><div class="input-row"><input id="fAmount" class="amount-input" type="number" inputmode="numeric" placeholder="0" value="${esc(draft.amount)}"></div></div><div class="field"><label>Ngày giao dịch</label><div class="input-row">${icon('calendar')}<input id="fDate" type="date" value="${esc(draft.date)}"></div></div><div class="field"><label>Tài khoản / Nguồn tiền</label><div class="input-row">${icon('wallet')}<select id="fSource">${SOURCES.map(v=>`<option ${draft.source===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="field"><label>Danh mục</label><div class="input-row">${icon('note')}<select id="fCat">${CATS.map(v=>`<option ${draft.category===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="field"><label>Ghi chú</label><div class="input-row">${icon('note')}<input id="fNote" value="${esc(draft.note)}" placeholder="Thêm ghi chú..."></div></div><div class="field"><label>Đính kèm hóa đơn</label><div class="attach-box"><button class="attach-btn" id="cameraBtn">${icon('camera')}<span>Chụp ảnh</span></button><button class="attach-btn" id="fileBtn">${icon('file')}<span>Ảnh / PDF</span></button><div class="attach-note" id="attachNote">${attachment?esc(attachment.name):'Ảnh hoặc PDF · tối đa 10MB'}</div><input id="attachInput" type="file" accept="image/*,application/pdf" hidden></div></div><button class="save-btn" id="saveTx">${editing?'Lưu thay đổi':'Lưu giao dịch'}</button>${editing?'<button class="save-btn" id="deleteTx" style="margin-top:8px;background:transparent;color:var(--red);border:1px solid var(--line)">Xóa giao dịch</button>':''}</div>`}
function plan(){const c=calc(),b=c.s.budgets||[],limit=b.reduce((s,x)=>s+(+x.limit||0),0),used=limit?Math.min(100,Math.round(c.spend/limit*100)):0,remain=Math.max(0,limit-c.spend),g=c.s.goal||{name:'Mục tiêu tiết kiệm',target:0,saved:c.savings},gp=g.target?Math.min(100,Math.round((+g.saved||0)/(+g.target||1)*100)):0;return`<div class="page-head"><h1>Kế hoạch</h1><span></span></div><div class="section-head"><h2>Ngân sách ${ml(c.ym).toLowerCase()}</h2><span>${used}%</span></div><div class="panel budget-card"><div class="ring-row"><div class="budget-ring" style="--pct:${used}%"><b>${used}%</b></div><div class="budget-meta"><div><small>Ngân sách</small><b>${fmt(limit)}đ</b></div><div><small>Còn lại</small><b>${fmt(remain)}đ</b></div></div></div></div><div class="section-head"><h2>Mục tiêu tiết kiệm</h2></div><div class="panel goal-card"><div><b>${esc(g.name||'Mục tiêu tiết kiệm')}</b><small>${fmt(g.saved||c.savings)}đ / ${fmt(g.target||0)}đ · ${gp}%</small><div class="meter"><i style="width:${gp}%"></i></div></div><div class="goal-art"></div></div><div class="section-head"><h2>Phong bì tháng</h2></div><div class="panel settings-card">${b.length?b.map(x=>{const spent=c.rows.filter(t=>typeOf(t)==='spending'&&(t.category||'Khác')===x.name).reduce((s,t)=>s+(+t.amount||0),0),p=x.limit?Math.min(100,Math.round(spent/x.limit*100)):0;return`<div class="setting"><span class="set-icon">${icon('plan')}</span><span><b>${esc(x.name)}</b><small>${fmt(spent)}đ / ${fmt(x.limit)}đ</small><div class="meter"><i style="width:${p}%"></i></div></span><button>${p}%</button></div>`}).join(''):'<div class="empty">Chưa có ngân sách.</div>'}</div>`}
function settings(){const c=calc(),dark=localStorage.getItem(THEME)==='dark';return`<div class="page-head"><h1>Cài đặt</h1><span></span></div><div class="panel settings-card"><div class="setting"><span class="set-icon">${icon('moon')}</span><span><b>Chế độ giao diện</b><small>${dark?'Tối':'Sáng'}</small></span><button id="themeInline">Đổi ›</button></div><div class="setting"><span class="set-icon">${icon('wallet')}</span><span><b>Số dư</b><small>Tiền mặt ${fmt(c.cash)}đ · Tiết kiệm ${fmt(c.savings)}đ</small></span><button id="balances">Chỉnh ›</button></div></div><div class="section-head"><h2>Dữ liệu</h2></div><div class="panel settings-card"><div class="setting"><span class="set-icon">${icon('cloud')}</span><span><b>Sao lưu</b><small>Lưu bản JSON trên thiết bị</small></span><button id="exportBtn">Xuất ›</button></div><div class="setting"><span class="set-icon">${icon('upload')}</span><span><b>Khôi phục</b><small>Đọc file backup JSON</small></span><button id="importBtn">Nhập ›</button></div><div class="setting"><span class="set-icon">${icon('trash')}</span><span><b>Xóa dữ liệu</b><small>Không thể hoàn tác</small></span><button class="danger" id="resetBtn">Xóa ›</button></div></div><input id="importFile" type="file" accept="application/json" hidden>`}
function render(){document.body.classList.toggle('add-mode',page==='add');const root=$('#screen');root.innerHTML=page==='home'?home():page==='flow'?flow():page==='add'?add():page==='plan'?plan():settings();bind();$$('.bottom-nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#addBtn')?.classList.toggle('active',page==='add')}
function bind(){
$$('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();scrollTo({top:0,behavior:'smooth'})});
$$('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;const t=load().transactions.find(x=>String(x.id)===String(editing));initDraft(t);page='add';render();scrollTo({top:0,behavior:'smooth'})});
$$('[data-filter]').forEach(b=>b.onclick=()=>{flowFilter=b.dataset.filter;render()});
$$('[data-month]').forEach(b=>b.onclick=()=>{if(b.dataset.month){month=b.dataset.month;render()}});
$('#search')?.addEventListener('input',e=>{query=e.target.value;const pos=e.target.selectionStart;render();const n=$('#search');if(n){n.focus();n.setSelectionRange(pos,pos)}});
$('#focusSearch')?.addEventListener('click',()=>$('#search')?.focus());
$('#backAdd')?.addEventListener('click',()=>{page='home';editing=null;render()});
$$('[data-type]').forEach(b=>b.onclick=()=>{draft.type=b.dataset.type==='income'?'income':'spending';render()});
$$('[data-cat]').forEach(b=>b.onclick=()=>{draft.category=b.dataset.cat;render()});
$('#fAmount')?.addEventListener('input',e=>draft.amount=e.target.value);$('#fDate')?.addEventListener('change',e=>draft.date=e.target.value);$('#fSource')?.addEventListener('change',e=>draft.source=e.target.value);$('#fCat')?.addEventListener('change',e=>{draft.category=e.target.value;render()});$('#fNote')?.addEventListener('input',e=>draft.note=e.target.value);
const pick=()=>$('#attachInput')?.click();$('#cameraBtn')?.addEventListener('click',pick);$('#fileBtn')?.addEventListener('click',pick);$('#attachInput')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024){alert('File lớn hơn 10MB.');return}attachment={name:f.name,type:f.type,size:f.size};$('#attachNote').textContent=f.name});
$('#saveTx')?.addEventListener('click',saveTx);$('#deleteTx')?.addEventListener('click',deleteTx);
$('#themeInline')?.addEventListener('click',toggleTheme);$('#balances')?.addEventListener('click',openBalances);$('#exportBtn')?.addEventListener('click',exportData);$('#importBtn')?.addEventListener('click',()=>$('#importFile')?.click());$('#importFile')?.addEventListener('change',e=>importData(e.target.files?.[0]));$('#resetBtn')?.addEventListener('click',()=>{if(confirm('Xóa toàn bộ dữ liệu trên thiết bị này?')){localStorage.removeItem(KEY);render()}})
}
function openAdd(){editing=null;initDraft(null);page='add';render();scrollTo({top:0,behavior:'smooth'})}
function saveTx(){const amount=Number(draft.amount);if(!amount)return alert('Nhập số tiền trước nha.');const s=load(),obj={id:editing||`tx_${Date.now()}`,type:draft.type,amount,date:draft.date,category:draft.category,source:draft.source,note:draft.note};if(attachment)obj.attachment={name:attachment.name,type:attachment.type,size:attachment.size};const i=s.transactions.findIndex(x=>String(x.id)===String(editing));if(i>=0)s.transactions[i]={...s.transactions[i],...obj};else s.transactions.push(obj);save(s);editing=null;page='flow';render();scrollTo({top:0,behavior:'smooth'})}
function deleteTx(){if(!editing||!confirm('Xóa giao dịch này?'))return;const s=load();s.transactions=s.transactions.filter(x=>String(x.id)!==String(editing));save(s);editing=null;page='flow';render()}
function toggleTheme(){const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem(THEME,next);render()}
function showSheet(html){const o=$('#overlay');o.innerHTML=`<div class="sheet">${html}</div>`;o.classList.add('show');o.onclick=e=>{if(e.target===o){o.classList.remove('show');o.innerHTML=''}}}
function openBalances(){const c=calc();showSheet(`<h2>Chỉnh số dư</h2><div class="field"><label>Tiền mặt</label><div class="input-row"><input id="cashBal" type="number" value="${c.cash}"></div></div><div class="field"><label>Tiết kiệm</label><div class="input-row"><input id="saveBal" type="number" value="${c.savings}"></div></div><div class="sheet-actions"><button class="secondary" id="closeBal">Hủy</button><button class="primary" id="saveBal">Lưu</button></div>`);$('#closeBal').onclick=()=>$('#overlay').classList.remove('show');$('#saveBal').onclick=()=>{const s=load();function setAcc(name,balance){const i=s.accounts.findIndex(a=>String(a.name||'').toLowerCase()===name.toLowerCase());const obj={...(i>=0?s.accounts[i]:{}),name,balance:+balance||0};if(i>=0)s.accounts[i]=obj;else s.accounts.push(obj)}setAcc('Tiền mặt',$('#cashBal').value);setAcc('Tiết kiệm',$('#saveBal').value);save(s);$('#overlay').classList.remove('show');render()}}
function exportData(){const blob=new Blob([JSON.stringify(load(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`money-journal-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const s=JSON.parse(r.result);localStorage.setItem(KEY,JSON.stringify(s));render();alert('Đã khôi phục dữ liệu.')}catch{alert('File không hợp lệ.')}};r.readAsText(file)}
$('#addBtn')?.addEventListener('click',openAdd);$('#themeBtn')?.addEventListener('click',toggleTheme);initDraft(null);render();
})();