(() => {
  let provider = 'other';
  const $ = id => document.getElementById(id);
  const providerLabel = p => ({vpbank:'VPBank',shinhan:'Shinhan',paylater:'Ví Trả Sau',other:'Khác'})[p] || 'Khác';
  const defaultAccount = p => ({vpbank:'VPBank Credit',shinhan:'Shinhan Credit',paylater:'Ví Trả Sau',other:'Sao kê'})[p] || 'Sao kê';

  function mountV21(){
    const sectionBtn=[...document.querySelectorAll('.section-title .link')].find(x=>x.textContent.includes('Xem activity'));
    if(sectionBtn){sectionBtn.textContent='Xem analytics →';sectionBtn.onclick=openAnalytics}
    const scan=document.querySelector('#scan .scan-box');
    if(scan){scan.innerHTML=`<div class="cam">📷</div><b>Ảnh hoặc PDF sao kê</b><p>OCR tạo giao dịch nháp để bạn review. V2.1 tự nhận diện VPBank / Shinhan / Ví Trả Sau, cảnh báo dòng có khả năng trùng và không tự lưu.</p><div class="provider-row"><div><label>Nguồn sao kê</label><select id="statementSource"><option value="auto">Tự nhận diện</option><option value="vpbank">VPBank</option><option value="shinhan">Shinhan</option><option value="paylater">Ví Trả Sau</option><option value="other">Khác</option></select></div><div><label>Tài khoản mặc định</label><input id="statementAccount" placeholder="VD: Shinhan Credit"></div></div><input id="statementFile" type="file" accept="image/*,application/pdf" capture="environment" hidden onchange="scanStatement(this.files[0])"><button class="btn" style="margin-top:12px" onclick="document.getElementById('statementFile').click()">🖼️ Chọn ảnh / PDF</button>`}
    const status=$('ocrStatus');
    if(status && !$('reviewTools')) status.insertAdjacentHTML('afterend','<div id="reviewTools" class="review-tools" style="display:none"><div><button class="btn secondary" onclick="toggleCandidates(true)">Chọn tất cả</button> <button class="btn secondary" onclick="toggleCandidates(false)">Bỏ chọn</button></div><span id="providerDetected" class="tiny-chip"></span></div><div id="reviewSummary" class="review-summary" style="display:none"></div>');
    if(!$('analyticsSheet')) document.body.insertAdjacentHTML('beforeend','<div id="analyticsSheet" class="sheet-wrap"><div class="sheet-back" onclick="closeSheet(\'analyticsSheet\')"></div><div class="sheet"><div class="handle"></div><h2>Analytics tháng này</h2><div id="analyticsKpis" class="analytics-grid"></div><div class="section-title" style="margin-top:12px"><span>Chi tiêu theo category</span><span class="tiny-chip">Net of refund</span></div><div id="categoryBars" class="card"></div><div id="analyticsInsight" class="insight-box" style="margin-top:12px"></div></div></div>');
  }

  window.openAnalytics = function(){
    const s=summary(), tx=state.transactions.filter(x=>monthKey(x.date)), spends=tx.filter(x=>x.type==='spending'), refunds=tx.filter(x=>x.type==='refund');
    const avg=spends.length?s.spend/spends.length:0, largest=spends.reduce((m,x)=>!m||Number(x.amount)>Number(m.amount)?x:m,null);
    $('analyticsKpis').innerHTML=`<div class="analytics-kpi"><span>Chi tiêu ròng</span><b>${fmt(s.netSpend)}</b></div><div class="analytics-kpi"><span>Giao dịch chi</span><b>${spends.length}</b></div><div class="analytics-kpi"><span>TB / giao dịch</span><b>${fmt(avg)}</b></div><div class="analytics-kpi"><span>Refund</span><b>${fmt(s.refund)}</b></div>`;
    const cats={};spends.forEach(x=>cats[x.category||'Khác']=(cats[x.category||'Khác']||0)+Number(x.amount||0));refunds.forEach(x=>cats[x.category||'Khác']=(cats[x.category||'Khác']||0)-Number(x.amount||0));
    const rows=Object.entries(cats).map(([n,v])=>[n,Math.max(0,v)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]), max=rows[0]?.[1]||1;
    $('categoryBars').innerHTML=rows.length?rows.slice(0,7).map(([n,v])=>`<div class="bar-row"><div class="bar-label">${esc(n)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.round(v/max*100)}%"></div></div><div class="bar-val">${fmt(v)}</div></div>`).join(''):'<div class="empty"><div class="emoji">📊</div>Chưa có chi tiêu tháng này.</div>';
    const top=rows[0], share=top&&s.netSpend?Math.round(top[1]/s.netSpend*100):0;
    $('analyticsInsight').innerHTML=largest?`💡 Chi lớn nhất: <b>${esc(largest.name)}</b> ${fmt(largest.amount)}. ${top?`Category cao nhất là <b>${esc(top[0])}</b>, khoảng ${share}% chi tiêu ròng.`:''}`:'Thêm giao dịch để bắt đầu thấy insight theo tháng.';
    $('analyticsSheet').classList.add('show');
  };

  const detectProvider = text => {const s=text.toLowerCase();if(/vpbank|vietnam prosperity|thịnh vượng|thinh vuong/.test(s))return'vpbank';if(/shinhan/.test(s))return'shinhan';if(/ví trả sau|vi tra sau|paylater|momo/.test(s))return'paylater';return'other'};
  const parseMoneyV21 = s => {if(!s)return 0;let neg=/^-/.test(s),t=s.replace(/[^\d.,]/g,''),ld=t.lastIndexOf('.'),lc=t.lastIndexOf(','),pos=Math.max(ld,lc);if(pos>-1&&t.length-pos-1===2)t=t.slice(0,pos).replace(/[.,]/g,'')+'.'+t.slice(pos+1);else t=t.replace(/[.,]/g,'');const n=parseFloat(t)||0;return neg?-n:n};
  const cleanMerchant = s => s.replace(/\b(VND|VN\/HANOI|VN\/HCM|HO CHI MINH|HA NOI)\b/gi,'').replace(/Primary VISA.*Card/gi,'').replace(/Retail VNM/gi,'').replace(/\s{2,}/g,' ').trim();
  const guessTypeV21 = (line,raw) => {const s=line.toLowerCase();if(/refund|hoàn|hoan tien|reversal/.test(s))return['refund','Từ khóa hoàn tiền'];if(/payment|thanh toán dư nợ|thanh toan du no|paid during|credit account/.test(s))return['debt_payment','Từ khóa thanh toán dư nợ'];if(/salary|lương|luong/.test(s))return['income','Từ khóa lương'];if(/transfer in|nhận tiền|nhan tien|received/.test(s))return['money_in','Từ khóa tiền vào'];if(/^\+/.test(raw))return['money_in','Số tiền dương'];return['spending','Mặc định giao dịch mua hàng']};
  const guessCategory = (name,line) => {const s=(name+' '+line).toLowerCase();if(/grab|be |taxi|xanh sm/.test(s))return'Di chuyển';if(/shopee|tiktok|lazada|mall|cellphone/.test(s))return'Mua sắm';if(/cgv|cinema|galaxy/.test(s))return'Hẹn hò';if(/food|restaurant|cafe|coffee|winmart|manwah/.test(s))return'Ăn uống';if(/apple.com|itunes|google/.test(s))return'Digital';if(/fee|phí|phi /.test(s))return'Phí';return'Khác'};
  const similar = (a,b) => {a=String(a||'').toLowerCase();b=String(b||'').toLowerCase();if(a===b)return true;const wa=new Set(a.split(/\W+/).filter(x=>x.length>2));return b.split(/\W+/).filter(x=>x.length>2).some(x=>wa.has(x))};

  window.scanStatement = async function(file){
    if(!file)return;ocrRows=[];$('ocrCandidates').innerHTML='';$('saveCandidatesWrap').style.display='none';$('reviewTools').style.display='none';$('reviewSummary').style.display='none';$('ocrStatus').textContent='Đang chuẩn bị OCR… Lần đầu có thể hơi lâu vì trình duyệt tải model.';
    try{
      let texts=[];
      if(file.type==='application/pdf'){
        if(!window.pdfjsLib){const mod=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.min.mjs');window.pdfjsLib=mod;window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.worker.min.mjs'}
        const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,max=Math.min(pdf.numPages,6);
        for(let p=1;p<=max;p++){const page=await pdf.getPage(p),vp=page.getViewport({scale:1.65}),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:ctx,viewport:vp}).promise;const r=await Tesseract.recognize(c,'eng',{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`Trang ${p}/${max}: ${Math.round(m.progress*100)}%`}});texts.push(r.data.text)}
      } else {const r=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`OCR ảnh: ${Math.round(m.progress*100)}%`}});texts=[r.data.text]}
      const text=texts.join('\n'),manual=$('statementSource').value;provider=manual==='auto'?detectProvider(text):manual;$('providerDetected').textContent=`Nguồn: ${providerLabel(provider)}`;if(!$('statementAccount').value)$('statementAccount').value=defaultAccount(provider);
      const lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean),dateRe=/\b(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})\b/,amountRe=/[-+]?\d{1,3}(?:[.,]\d{3})+(?:[.,]\d{2})?|[-+]?\d{5,}/g,seen=new Set();
      for(const line of lines){const dm=line.match(dateRe),nums=line.match(amountRe);if(!nums?.length)continue;const raw=nums[nums.length-1],amt=parseMoneyV21(raw);if(!amt||Math.abs(amt)<1000)continue;let date=new Date().toISOString().slice(0,10);if(dm){let y=+dm[3];if(y<100)y+=2000;date=`${y}-${String(dm[2]).padStart(2,'0')}-${String(dm[1]).padStart(2,'0')}`};const name=cleanMerchant(line.replace(dateRe,'').replace(raw,'')).slice(0,70)||'Giao dịch OCR',[type,reason]=guessTypeV21(line,raw),key=[date,name.toLowerCase().replace(/\W/g,''),Math.abs(amt)].join('|');if(seen.has(key))continue;seen.add(key);let conf=45+(dm?20:0)+10+(name.length>3?10:0)+(!reason.includes('Mặc định')?10:0);const dup=state.transactions.some(x=>x.date===date&&Math.abs(Number(x.amount)-Math.abs(amt))<1&&similar(x.name,name));ocrRows.push({selected:!dup,name,date,amount:Math.abs(amt),type,category:guessCategory(name,line),account:$('statementAccount').value||defaultAccount(provider),raw:line,confidence:Math.min(95,conf),reason,duplicate:dup});if(ocrRows.length>=40)break}
      if(!ocrRows.length){$('ocrStatus').textContent='OCR xong nhưng chưa tách được dòng giao dịch. Thử crop sát bảng giao dịch hoặc chọn đúng nguồn sao kê rồi scan lại.';return}
      $('ocrStatus').textContent=`Đã tạo ${ocrRows.length} giao dịch nháp.`;renderCandidates();$('reviewTools').style.display='flex';$('reviewSummary').style.display='grid';$('saveCandidatesWrap').style.display='block';updateReviewSummary();
    }catch(e){console.error(e);$('ocrStatus').textContent='OCR chưa chạy được trên file này. Thử ảnh JPG/PNG rõ hơn hoặc thêm giao dịch thủ công.'}
  };

  window.renderCandidates = function(){
    $('ocrCandidates').innerHTML=ocrRows.map((r,i)=>`<div class="candidate"><div class="candidate-head"><input type="checkbox" ${r.selected?'checked':''} onchange="ocrRows[${i}].selected=this.checked;updateReviewSummary()"><span class="confidence ${r.confidence<60?'low':r.confidence<80?'med':''}">${r.confidence}% tin cậy</span>${r.duplicate?'<span class="confidence dupe">Có thể trùng</span>':''}<span class="tiny-chip">${esc(providerLabel(provider))}</span></div><div style="font-size:9px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(r.raw.slice(0,130))}</div><div class="candidate-grid"><input type="text" value="${escAttr(r.name)}" onchange="ocrRows[${i}].name=this.value"><input type="number" inputmode="numeric" value="${r.amount}" onchange="ocrRows[${i}].amount=Number(this.value);updateReviewSummary()"><input type="date" value="${r.date}" onchange="ocrRows[${i}].date=this.value"><select onchange="ocrRows[${i}].type=this.value;updateReviewSummary()">${['spending','income','money_in','debt_payment','refund','transfer'].map(t=>`<option value="${t}" ${r.type===t?'selected':''}>${typeLabel(t)}</option>`).join('')}</select><input type="text" value="${escAttr(r.category)}" placeholder="Category" onchange="ocrRows[${i}].category=this.value"><input type="text" value="${escAttr(r.account)}" placeholder="Tài khoản" onchange="ocrRows[${i}].account=this.value"></div><div class="candidate-note">Gợi ý: ${esc(r.reason)}${r.duplicate?' • Dòng này bị bỏ chọn vì có khả năng đã lưu.':''}</div></div>`).join('')
  };
  window.updateReviewSummary = function(){const rows=ocrRows.filter(r=>r.selected),sp=rows.filter(r=>r.type==='spending').reduce((a,r)=>a+Number(r.amount||0),0),debt=rows.filter(r=>r.type==='debt_payment').reduce((a,r)=>a+Number(r.amount||0),0),dup=ocrRows.filter(r=>r.duplicate).length;$('reviewSummary').innerHTML=`<div class="review-stat"><span>Đang chọn</span><b>${rows.length}/${ocrRows.length}</b></div><div class="review-stat"><span>Spending</span><b>${fmt(sp)}</b></div><div class="review-stat"><span>Debt pay</span><b>${fmt(debt)}</b></div>`;if(dup)$('ocrStatus').textContent=`Đã tạo ${ocrRows.length} giao dịch nháp • ${dup} dòng có khả năng trùng đã tự bỏ chọn.`};
  window.toggleCandidates = function(v){ocrRows.forEach(r=>r.selected=v&&!r.duplicate);renderCandidates();updateReviewSummary()};
  window.saveCandidates = function(){const rows=ocrRows.filter(r=>r.selected&&r.amount>0);if(!rows.length){alert('Chọn ít nhất 1 dòng');return}rows.forEach(r=>state.transactions.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),type:r.type,amount:Number(r.amount),date:r.date,name:r.name,category:r.category||'Khác',account:r.account||defaultAccount(provider),note:`Imported from ${providerLabel(provider)} statement OCR`}));ocrRows=[];$('ocrCandidates').innerHTML='';$('saveCandidatesWrap').style.display='none';$('reviewTools').style.display='none';$('reviewSummary').style.display='none';$('ocrStatus').textContent=`Đã lưu ${rows.length} giao dịch. Mở Activity để kiểm tra lại.`;saveState()};

  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',mountV21); else mountV21();
})();
