(() => {
  const $ = id => document.getElementById(id);
  const TYPE_LABELS={spending:'Chi tiêu',income:'Thu nhập',money_in:'Tiền nhận',debt_payment:'Trả thẻ',refund:'Hoàn tiền',transfer:'Chuyển tiền'};
  const CATS=['Ăn uống','Di chuyển','Mua sắm','Hẹn hò','Giải trí','Gym & sức khỏe','Làm đẹp','Hóa đơn','Dịch vụ số','Quà tặng','Phí','Trả góp','Khác'];
  let rows=[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const parseMoney=s=>{let t=String(s||'').replace(/[^\d.,-]/g,''),neg=t.startsWith('-');t=t.replace(/-/g,'');const ld=t.lastIndexOf('.'),lc=t.lastIndexOf(','),p=Math.max(ld,lc);if(p>-1&&t.length-p-1===2)t=t.slice(0,p).replace(/[.,]/g,'')+'.'+t.slice(p+1);else t=t.replace(/[.,]/g,'');const n=parseFloat(t)||0;return neg?-n:n};
  const detectBank=text=>{const s=text.toLowerCase();if(/vpbank|vietnam prosperity|vpb_|idt:|cash installment/.test(s))return'vpbank';if(/shinhan|primary visa|retail vnm|shinhan point/.test(s))return'shinhan';if(/momo|ví trả sau|vi tra sau|paylater/.test(s))return'momo';return'unknown'};
  const categoryFor=s=>{s=s.toLowerCase();if(/grab|xanh sm|taxi|be\b/.test(s))return'Di chuyển';if(/shopee|lazada|tiktok|cellphone|uniqlo|zara|hm\b/.test(s))return'Mua sắm';if(/cgv|galaxy|cinema|lotte cinema/.test(s))return'Giải trí';if(/restaurant|cafe|coffee|highlands|phuc long|kfc|lotteria|winmart|manwah|food|grabfood/.test(s))return'Ăn uống';if(/gym|fitness|yoga/.test(s))return'Gym & sức khỏe';if(/beauty|spa|salon|watsons|guardian/.test(s))return'Làm đẹp';if(/electric|water|internet|phone|viettel|mobifone|vinaphone/.test(s))return'Hóa đơn';if(/apple\.com|itunes|google|netflix|spotify|youtube/.test(s))return'Dịch vụ số';if(/fee|phí|phi\b/.test(s))return'Phí';if(/installment|trả góp|tra gop/.test(s))return'Trả góp';return'Khác'};
  const typeFor=s=>{const x=s.toLowerCase();if(/refund|reversal|hoàn tiền|hoan tien/.test(x))return'refund';if(/payment|thanh toán dư nợ|thanh toan du no|paid during|payment received/.test(x))return'debt_payment';if(/salary|lương|luong/.test(x))return'income';if(/received|nhận tiền|nhan tien|transfer in/.test(x))return'money_in';if(/installment|cash installment|vpb_installment/.test(x))return'transfer';return'spending'};
  const rejectBlock=s=>/shinhan point|credit limit|hạn mức|han muc|available limit|customer|statement|summary|minimum payment|payment due|total amount due|total outstanding|số dư|so du|page \d+|card number|account number|hurry up|just spending|chi cin chi tieu|file name|\.pdf\b/i.test(s);

  function dateFrom(s){const m=s.match(/(?:^|\s)(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})(?=\s|$)/);if(!m)return null;let y=+m[3];if(y<100)y+=2000;const d=new Date(y,+m[2]-1,+m[1]);if(Number.isNaN(d.getTime()))return null;const now=new Date();const max=new Date(now);max.setDate(max.getDate()+2);const min=new Date(now);min.setFullYear(min.getFullYear()-2);if(d>max||d<min)return null;return {iso:`${y}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`,raw:m[0].trim()};}
  function transactionBlocks(text){const lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean),out=[];let cur='';for(const line of lines){const starts=/^\d{1,2}[\/\-.]\d{1,2}[\/\-.]\d{2,4}\b/.test(line);if(starts){if(cur)out.push(cur);cur=line}else if(cur){cur+=' '+line}}if(cur)out.push(cur);return out;}
  function chooseAmount(block){const nums=[...block.matchAll(/[-+]?\d{1,3}(?:[.,]\d{3})+(?:[.,]\d{2})?|[-+]?\d{4,}(?:[.,]\d{2})?/g)].map(m=>({raw:m[0],n:parseMoney(m[0])})).filter(x=>Math.abs(x.n)>=1000&&Math.abs(x.n)<=200000000);if(!nums.length)return null;return nums[nums.length-1];}
  function cleanName(block,dateRaw,amountRaw){let s=block.replace(dateRaw,' ').replace(amountRaw,' ').replace(/\b(VND|VN\/HANOI|VN\/HCM|HO CHI MINH|HA NOI|Retail VNM|Primary VISA[^ ]*)\b/gi,' ').replace(/\s+/g,' ').trim();return s.slice(0,64)||'Giao dịch';}
  function parseBank(text){const bank=detectBank(text),out=[],seen=new Set();for(const block of transactionBlocks(text)){if(rejectBlock(block))continue;const d=dateFrom(block);if(!d)continue;const amt=chooseAmount(block);if(!amt)continue;const name=cleanName(block,d.raw,amt.raw);if(name.length<3)continue;let type=typeFor(block),category=categoryFor(block);if(bank==='vpbank'&&/IDT:|cash installment|vpb_installment/i.test(block)){type='transfer';category='Trả góp'}if(bank==='shinhan'&&/payment received|thanh toán dư nợ/i.test(block))type='debt_payment';const r={selected:true,name,date:d.iso,amount:Math.abs(amt.n),type,category,account:bank==='vpbank'?'VPBank':bank==='shinhan'?'Shinhan':bank==='momo'?'Ví Trả Sau':'Sao kê'};const key=[r.date,r.amount,r.name.toLowerCase().replace(/\W/g,'')].join('|');if(!seen.has(key)){seen.add(key);out.push(r)}}return {bank,rows:out};}

  function mount(){const scan=document.querySelector('#scan .scan-box, #scan .scan');if(!scan)return;document.body.classList.add('v27');scan.innerHTML=`<div class="scan-v25-head"><div class="scan-v25-icon">🧾</div><div><h3>Quét sao kê</h3><p>Chọn ảnh. App chỉ giữ dòng giống giao dịch thật.</p></div></div><div class="scan-v25-actions"><button id="v27Pick" class="scan-v25-btn primary">🖼️ Chọn ảnh <small>Tối đa 10</small></button><button id="v27Pdf" class="scan-v25-btn">📄 Chọn PDF <small>1 file</small></button></div><input id="v27Images" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple hidden><input id="v27PdfFile" type="file" accept="application/pdf" hidden><div id="v27Progress" class="scan-v25-progress" hidden><div class="scan-v25-progress-top"><span class="scan-v25-spinner"></span><div><b id="v27Title">Đang quét…</b><small id="v27Sub">Đang nhận diện giao dịch</small></div><span id="v27Count"></span></div><div class="scan-v25-track"><i id="v27Bar"></i></div></div><div id="v27Result"></div>`;$('v27Pick').onclick=()=>$('v27Images').click();$('v27Pdf').onclick=()=>$('v27PdfFile').click();$('v27Images').onchange=async e=>{const fs=Array.from(e.target.files||[]).slice(0,10);if(fs.length)await scanImages(fs);e.target.value=''};$('v27PdfFile').onchange=async e=>{const f=e.target.files?.[0];if(f)await scanPdf(f);e.target.value=''};}
  function prog(done,total,title,sub){const b=$('v27Progress');b.hidden=false;b.className='scan-v25-progress busy';$('v27Title').textContent=title;$('v27Sub').textContent=sub||'Đang nhận diện giao dịch';$('v27Count').textContent=`${done}/${total}`;$('v27Bar').style.width=Math.max(5,Math.round(done/total*100))+'%'}
  function finish(title,ok=true){const b=$('v27Progress');b.className='scan-v25-progress '+(ok?'done':'error');$('v27Title').textContent=title;$('v27Sub').textContent=ok?'Kiểm tra trước khi lưu':'Thử lại với ảnh rõ hơn';$('v27Bar').style.width=ok?'100%':'20%'}
  async function ocr(file,i,total){if(!window.Tesseract)throw new Error('OCR chưa tải');const r=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')prog(i-1,total,`Đang quét ảnh ${i}/${total}`,`Nhận diện ${Math.round((m.progress||0)*100)}%`)}});return r.data.text||''}
  async function scanImages(files){rows=[];$('v27Result').innerHTML='';$('v27Pick').disabled=$('v27Pdf').disabled=true;try{const seen=new Set();let banks=new Set();for(let i=0;i<files.length;i++){prog(i,files.length,`Đang quét ảnh ${i+1}/${files.length}`,'Đang tìm giao dịch thật');const text=await ocr(files[i],i+1,files.length);const p=parseBank(text);banks.add(p.bank);for(const r of p.rows){const k=[r.date,r.amount,r.name].join('|');if(!seen.has(k)){seen.add(k);rows.push(r)}}}render([...banks]);finish(rows.length?`Xong · ${rows.length} giao dịch`:'Không tìm thấy giao dịch',!!rows.length)}catch(e){console.error(e);finish('Quét bị lỗi',false)}finally{$('v27Pick').disabled=$('v27Pdf').disabled=false}}
  async function scanPdf(file){rows=[];$('v27Result').innerHTML='';$('v27Pick').disabled=$('v27Pdf').disabled=true;try{prog(0,1,'Đang đọc PDF…','Đang tách từng trang');if(!window.pdfjsLib){const mod=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.min.mjs');window.pdfjsLib=mod;window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.worker.min.mjs'}const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let full='';for(let p=1;p<=Math.min(pdf.numPages,6);p++){const page=await pdf.getPage(p),vp=page.getViewport({scale:1.6}),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:ctx,viewport:vp}).promise;full+='\n'+await ocr(c,p,Math.min(pdf.numPages,6))}const parsed=parseBank(full);rows=parsed.rows;render([parsed.bank]);finish(rows.length?`Xong · ${rows.length} giao dịch`:'Không tìm thấy giao dịch',!!rows.length)}catch(e){console.error(e);finish('Quét bị lỗi',false)}finally{$('v27Pick').disabled=$('v27Pdf').disabled=false}}
  function render(banks){const root=$('v27Result');if(!rows.length){root.innerHTML='';return}const bankTxt=banks.filter(x=>x&&x!=='unknown').map(x=>x==='vpbank'?'VPBank':x==='shinhan'?'Shinhan':x==='momo'?'Ví Trả Sau':x).join(' + ');root.innerHTML=`<div class="scan-v25-summary"><b>${rows.length} giao dịch</b><span>${bankTxt||'Sao kê'}</span></div><div class="scan-v25-list">${rows.map((r,i)=>`<div class="scan-v25-row"><input type="checkbox" ${r.selected?'checked':''} data-i="${i}" class="v27sel"><div class="scan-v25-main"><input class="v27name" data-i="${i}" value="${esc(r.name)}"><small>${r.date}</small><div style="display:flex;gap:6px;margin-top:6px"><select class="v27type" data-i="${i}">${Object.entries(TYPE_LABELS).map(([k,v])=>`<option value="${k}" ${r.type===k?'selected':''}>${v}</option>`).join('')}</select><select class="v27cat" data-i="${i}">${CATS.map(c=>`<option ${r.category===c?'selected':''}>${c}</option>`).join('')}</select></div></div><input class="v27amt" data-i="${i}" type="number" inputmode="numeric" value="${r.amount}"></div>`).join('')}</div><button id="v27Save" class="scan-v25-save">Lưu giao dịch</button>`;root.querySelectorAll('.v27sel').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].selected=e.target.checked);root.querySelectorAll('.v27name').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].name=e.target.value);root.querySelectorAll('.v27amt').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].amount=+e.target.value);root.querySelectorAll('.v27type').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].type=e.target.value);root.querySelectorAll('.v27cat').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].category=e.target.value);$('v27Save').onclick=saveRows;}
  function saveRows(){const chosen=rows.filter(r=>r.selected&&r.amount);if(!chosen.length)return;try{if(typeof state==='undefined'||!Array.isArray(state.transactions))throw new Error('state');for(const r of chosen)state.transactions.unshift({id:Date.now()+Math.random(),name:r.name,amount:+r.amount,date:r.date,type:r.type,category:r.category,account:r.account,note:'Nhập từ sao kê'});if(typeof save==='function')save();else localStorage.setItem('moneyJournalV2',JSON.stringify(state));$('v27Result').innerHTML=`<div class="scan-v25-saved">✓ Đã lưu ${chosen.length} giao dịch</div>`}catch(e){console.error(e);$('v27Result').innerHTML='<div class="scan-v25-error">Không lưu được. Thử lại.</div>'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,1700));else setTimeout(mount,1700);
})();