(() => {
  const $=id=>document.getElementById(id);
  const TYPES={spending:'Chi tiêu',income:'Thu nhập',money_in:'Tiền nhận',debt_payment:'Trả thẻ',refund:'Hoàn tiền',transfer:'Chuyển tiền'};
  const CATS=['Ăn uống','Di chuyển','Mua sắm','Hẹn hò','Giải trí','Gym & sức khỏe','Làm đẹp','Hóa đơn','Dịch vụ số','Quà tặng','Phí','Trả góp','Khác'];
  let rows=[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const fmt=n=>(Number(n)||0).toLocaleString('vi-VN');
  const parseAmount=s=>Number(String(s||'').replace(/[^\d-]/g,''))||0;
  const money=s=>{let t=String(s||'').replace(/[^\d.,-]/g,''),neg=t.startsWith('-');t=t.replace(/-/g,'');const p=Math.max(t.lastIndexOf('.'),t.lastIndexOf(','));if(p>-1&&t.length-p-1===2)t=t.slice(0,p).replace(/[.,]/g,'')+'.'+t.slice(p+1);else t=t.replace(/[.,]/g,'');const n=parseFloat(t)||0;return neg?-n:n};
  const bank=text=>/vpbank|vpb_|idt:|cash installment/i.test(text)?'VPBank':/shinhan|primary visa|retail vnm/i.test(text)?'Shinhan':/momo|ví trả sau|paylater/i.test(text)?'Ví Trả Sau':'Sao kê';
  const type=s=>/refund|reversal|hoàn tiền/i.test(s)?'refund':/credit account|payment received|thanh toán dư nợ/i.test(s)?'debt_payment':/salary|lương/i.test(s)?'income':/received|nhận tiền|transfer in/i.test(s)?'money_in':/installment|cash installment|vpb_installment|idt:/i.test(s)?'transfer':'spending';
  const cat=s=>/grab|xanh sm|taxi|\bbe\b/i.test(s)?'Di chuyển':/shopee|lazada|tiktok|uniqlo|zara/i.test(s)?'Mua sắm':/cgv|cinema|galaxy/i.test(s)?'Giải trí':/restaurant|cafe|coffee|highlands|phuc long|food|grabfood|winmart/i.test(s)?'Ăn uống':/gym|fitness|yoga/i.test(s)?'Gym & sức khỏe':/beauty|spa|salon|watsons|guardian/i.test(s)?'Làm đẹp':/apple\.com|itunes|google|netflix|spotify/i.test(s)?'Dịch vụ số':/fee|phí/i.test(s)?'Phí':/installment|idt:|cash installment/i.test(s)?'Trả góp':'Khác';
  const reject=s=>/shinhan point|credit limit|hạn mức|available limit|customer|statement|summary|minimum payment|payment due|total amount due|total outstanding|page \d+|card number|account number|hurry up|just spending|\.pdf\b/i.test(s);

  function allDates(s){return [...s.matchAll(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})\b/g)].map(m=>{let y=+m[3];if(y<100)y+=2000;return{raw:m[0],day:+m[1],month:+m[2],year:y,index:m.index}})}
  function dateOf(s){const dates=allDates(s);if(!dates.length)return null;const d0=dates[0];const d=new Date(d0.year,d0.month-1,d0.day),max=new Date(),min=new Date();max.setDate(max.getDate()+2);min.setFullYear(min.getFullYear()-2);if(Number.isNaN(d.getTime())||d>max||d<min)return null;return{raw:d0.raw,iso:`${d0.year}-${String(d0.month).padStart(2,'0')}-${String(d0.day).padStart(2,'0')}`}}
  function blocks(text){const lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean),out=[];let cur='';for(const line of lines){if(/^\d{1,2}[\/\-.]\d{1,2}[\/\-.]\d{2,4}\b/.test(line)){if(cur)out.push(cur);cur=line}else if(cur)cur+=' '+line}if(cur)out.push(cur);return out}
  function chooseAmount(s){const arr=[...s.matchAll(/[-+]?\d{1,3}(?:[.,]\d{3})+(?:[.,]\d{2})?|[-+]?\d{4,}(?:[.,]\d{2})?/g)].map((m,i)=>{const raw=m[0],n=money(raw),sep=/[.,]/.test(raw),dec=/[.,]\d{2}$/.test(raw),plain=/^\d{4,6}$/.test(raw);let score=(sep?7:0)+(dec?4:0)+(Math.abs(n)>=10000?2:0)+(plain?-6:0);return{raw,n,score,i}}).filter(x=>Math.abs(x.n)>=1000&&Math.abs(x.n)<=200000000);if(!arr.length)return null;arr.sort((a,b)=>b.score-a.score||Math.abs(b.n)-Math.abs(a.n)||a.i-b.i);return arr[0]}
  function niceName(s){const l=s.toLowerCase();if(/cash withdrawal/.test(l))return'Rút tiền mặt';if(/credit account|payment received|thanh toán dư nợ/.test(l))return'Thanh toán thẻ';if(/cash installment|vpb_installment|idt:/.test(l))return'Trả góp VPBank';if(/grab/.test(l))return'Grab';if(/shopee/.test(l))return'Shopee';return s.replace(/\b\d{1,2}[\/\-.]\d{1,2}[\/\-.]\d{2,4}\b/g,' ').replace(/[-+]?\d{1,3}(?:[.,]\d{3})+(?:[.,]\d{2})?|[-+]?\d{4,}(?:[.,]\d{2})?/g,' ').replace(/\b(VND|Retail VNM|Primary VISA\S*|HO CHI MINH|HA NOI)\b/gi,' ').replace(/[_|]+/g,' ').replace(/\s+/g,' ').trim().slice(0,46)}
  function parse(text){const b=bank(text),out=[],seen=new Set();for(const s of blocks(text)){if(reject(s))continue;const d=dateOf(s),a=chooseAmount(s);if(!d||!a)continue;const name=niceName(s);if(name.length<2||!/[A-Za-zÀ-ỹ]/.test(name))continue;const r={selected:true,name,date:d.iso,amount:Math.abs(a.n),type:type(s),category:cat(s),account:b};const k=[r.date,r.amount,r.name].join('|');if(!seen.has(k)){seen.add(k);out.push(r)}}return{bank:b,rows:out}}

  function mount(){const scan=document.querySelector('#scan .scan-box,#scan .scan');if(!scan)return;document.body.classList.add('v29');scan.innerHTML=`<div class="scan-v25-head"><div class="scan-v25-icon">🧾</div><div><h3>Quét sao kê</h3><p>Chọn ảnh, app tự lọc giao dịch.</p></div></div><div class="scan-v25-actions"><button id="v29Pick" class="scan-v25-btn primary">🖼️ Chọn ảnh <small>Tối đa 10</small></button><button id="v29Pdf" class="scan-v25-btn">📄 Chọn PDF <small>1 file</small></button></div><input id="v29Images" type="file" accept="image/*" multiple hidden><input id="v29PdfFile" type="file" accept="application/pdf" hidden><div id="v29Progress" class="scan-v25-progress" hidden><div class="scan-v25-progress-top"><span class="scan-v25-spinner"></span><div><b id="v29Title">Đang quét…</b><small id="v29Sub">Đang nhận diện giao dịch</small></div><span id="v29Count"></span></div><div class="scan-v25-track"><i id="v29Bar"></i></div></div><div id="v29Result"></div>`;$('v29Pick').onclick=()=>$('v29Images').click();$('v29Pdf').onclick=()=>$('v29PdfFile').click();$('v29Images').onchange=async e=>{const fs=Array.from(e.target.files||[]).slice(0,10);if(fs.length)await scanImages(fs);e.target.value=''};$('v29PdfFile').onchange=async e=>{const f=e.target.files?.[0];if(f)await scanPdf(f);e.target.value=''};}
  function prog(done,total,t,sub){const box=$('v29Progress');box.hidden=false;box.className='scan-v25-progress busy';$('v29Title').textContent=t;$('v29Sub').textContent=sub||'Đang nhận diện';$('v29Count').textContent=`${done}/${total}`;$('v29Bar').style.width=Math.max(5,Math.round(done/total*100))+'%'}
  function fin(t,ok){const box=$('v29Progress');box.className='scan-v25-progress '+(ok?'done':'error');$('v29Title').textContent=t;$('v29Sub').textContent=ok?'Kiểm tra trước khi lưu':'Thử ảnh rõ hơn';$('v29Bar').style.width=ok?'100%':'20%'}
  async function ocr(file,i,total){if(!window.Tesseract)throw new Error('OCR chưa tải');const r=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')prog(i-1,total,`Đang quét ảnh ${i}/${total}`,`Nhận diện ${Math.round((m.progress||0)*100)}%`)}});return r.data.text||''}
  async function scanImages(fs){rows=[];$('v29Result').innerHTML='';$('v29Pick').disabled=$('v29Pdf').disabled=true;try{const seen=new Set(),banks=new Set();for(let i=0;i<fs.length;i++){prog(i,fs.length,`Đang quét ảnh ${i+1}/${fs.length}`,'Đang lọc giao dịch');const p=parse(await ocr(fs[i],i+1,fs.length));banks.add(p.bank);for(const r of p.rows){const k=[r.date,r.amount,r.name].join('|');if(!seen.has(k)){seen.add(k);rows.push(r)}}}render([...banks]);fin(rows.length?`Xong · ${rows.length} giao dịch`:'Không tìm thấy giao dịch',!!rows.length)}catch(e){console.error(e);fin('Quét bị lỗi',false)}finally{$('v29Pick').disabled=$('v29Pdf').disabled=false}}
  async function scanPdf(file){rows=[];$('v29Result').innerHTML='';$('v29Pick').disabled=$('v29Pdf').disabled=true;try{prog(0,1,'Đang đọc PDF…','Đang tách trang');if(!window.pdfjsLib){const mod=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.min.mjs');window.pdfjsLib=mod;window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.worker.min.mjs'}const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let p=1;p<=Math.min(pdf.numPages,6);p++){const page=await pdf.getPage(p),vp=page.getViewport({scale:1.6}),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:ctx,viewport:vp}).promise;text+='\n'+await ocr(c,p,Math.min(pdf.numPages,6))}const x=parse(text);rows=x.rows;render([x.bank]);fin(rows.length?`Xong · ${rows.length} giao dịch`:'Không tìm thấy giao dịch',!!rows.length)}catch(e){console.error(e);fin('Quét bị lỗi',false)}finally{$('v29Pick').disabled=$('v29Pdf').disabled=false}}
  function render(banks){const root=$('v29Result');if(!rows.length){root.innerHTML='';return}root.innerHTML=`<div class="scan-v25-summary"><b>${rows.length} giao dịch</b><span>${banks.join(' + ')}</span></div><div class="scan-v25-list">${rows.map((r,i)=>`<div class="scan-v25-row"><input type="checkbox" ${r.selected?'checked':''} class="v29sel" data-i="${i}"><div class="scan-v25-main"><input class="v29name" data-i="${i}" value="${esc(r.name)}"><small>${r.date} · ${TYPES[r.type]}</small><div style="display:flex;gap:6px;margin-top:6px"><select class="v29type" data-i="${i}">${Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${r.type===k?'selected':''}>${v}</option>`).join('')}</select><select class="v29cat" data-i="${i}">${CATS.map(c=>`<option ${r.category===c?'selected':''}>${c}</option>`).join('')}</select></div></div><input class="v29amt" data-i="${i}" type="text" inputmode="numeric" value="${fmt(r.amount)}"></div>`).join('')}</div><button id="v29Save" class="scan-v25-save">Lưu giao dịch</button>`;root.querySelectorAll('.v29sel').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].selected=e.target.checked);root.querySelectorAll('.v29name').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].name=e.target.value);root.querySelectorAll('.v29amt').forEach(x=>{x.onfocus=e=>{const i=+e.target.dataset.i;e.target.value=String(rows[i].amount)};x.onblur=e=>{const i=+e.target.dataset.i;rows[i].amount=parseAmount(e.target.value);e.target.value=fmt(rows[i].amount)}});root.querySelectorAll('.v29type').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].type=e.target.value);root.querySelectorAll('.v29cat').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].category=e.target.value);$('v29Save').onclick=saveRows}
  function saveRows(){const chosen=rows.filter(r=>r.selected&&r.amount);if(!chosen.length)return;try{if(typeof state==='undefined'||!Array.isArray(state.transactions))throw new Error('state');for(const r of chosen)state.transactions.unshift({id:Date.now()+Math.random(),name:r.name,amount:+r.amount,date:r.date,type:r.type,category:r.category,account:r.account,note:'Nhập từ sao kê'});if(typeof save==='function')save();else localStorage.setItem('moneyJournalV2',JSON.stringify(state));$('v29Result').innerHTML=`<div class="scan-v25-saved">✓ Đã lưu ${chosen.length} giao dịch</div>`}catch(e){console.error(e);$('v29Result').innerHTML='<div class="scan-v25-error">Không lưu được. Thử lại.</div>'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,2500));else setTimeout(mount,2500);
})();