(() => {
  const $=id=>document.getElementById(id);
  const TYPES={spending:'Chi tiêu',income:'Thu nhập',money_in:'Tiền nhận',debt_payment:'Trả thẻ',refund:'Hoàn tiền',transfer:'Chuyển tiền'};
  const CATS=['Ăn uống','Di chuyển','Mua sắm','Hẹn hò','Giải trí','Gym & sức khỏe','Làm đẹp','Hóa đơn','Dịch vụ số','Quà tặng','Phí','Trả góp','Thanh toán dư nợ','Khác'];
  const SOURCES=['Ví Trả Sau','VPBank','Shinhan','Tiền mặt','Khác'];
  let rows=[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>(Number(n)||0).toLocaleString('vi-VN');
  const parseAmt=s=>Number(String(s||'').replace(/[^\d-]/g,''))||0;
  const dateISO=(d,m,y)=>{y=+y<100?2000+(+y):+y;return `${y}-${String(+m).padStart(2,'0')}-${String(+d).padStart(2,'0')}`};
  const dateVI=iso=>{const [y,m,d]=String(iso).split('-');return `${d}/${m}/${y}`};
  const detectSource=t=>/momo|ví trả sau|vi tra sau|paylater/i.test(t)?'Ví Trả Sau':/vpbank|vpb_|cash installment|idt:/i.test(t)?'VPBank':/shinhan|primary visa|retail vnm/i.test(t)?'Shinhan':'Khác';
  const numberTokens=s=>[...String(s).matchAll(/[+-]?\d{1,3}(?:[.,]\d{3})+(?:[.,]\d{2})?|[+-]?\d{4,9}/g)].map(m=>({raw:m[0],value:Math.abs(Number(m[0].replace(/[^\d-]/g,''))||0),index:m.index})).filter(x=>x.value>=1000&&x.value<=200000000);
  const closestAmount=(text,needle,preferred=[])=>{const i=text.toLowerCase().search(needle);if(i<0)return 0;const nums=numberTokens(text);if(!nums.length)return 0;for(const p of preferred){const hit=nums.find(n=>n.value===p);if(hit)return hit.value}nums.sort((a,b)=>Math.abs(a.index-i)-Math.abs(b.index-i));return nums[0].value};
  const add=(out,seen,r)=>{if(!r.amount||!r.date)return;const k=[r.date,r.amount,r.note.toLowerCase()].join('|');if(!seen.has(k)){seen.add(k);out.push({...r,selected:true})}};

  function parsePayLater(text){
    const out=[],seen=new Set();
    let body=text;
    const start=body.search(/giao\s*d[iị]ch\s*trong\s*th[aá]ng|giao dich trong thang/i); if(start>=0) body=body.slice(start);
    const end=body.search(/t[oổ]ng\s*dư\s*n[oợ]\s*t[oớ]i\s*h[aạ]n|tong du no toi han/i); if(end>0) body=body.slice(0,end);
    // Hard reject overview totals so 416k/449k never become transactions.
    body=body.replace(/t[oổ]ng\s*quan\s*dư\s*n[oợ][\s\S]*?(?=giao\s*d[iị]ch\s*trong\s*th[aá]ng)/gi,' ')
             .replace(/t[oổ]ng\s*dư\s*n[oợ]\s*th[aá]ng[^\n]*/gi,' ')
             .replace(/chi\s*ti[eê]u\s*th[aá]ng[^\n]*/gi,' ')
             .replace(/t[oổ]ng\s*ph[ií]\s*ph[aá]t\s*sinh[^\n]*/gi,' ');
    const dates=[...body.matchAll(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})\b/g)];
    for(let i=0;i<dates.length;i++){
      const m=dates[i], next=dates[i+1]; const chunk=body.slice(m.index,next?next.index:body.length); const date=dateISO(m[1],m[2],m[3]); const low=chunk.toLowerCase();
      if(/cgv|xem phim/.test(low)) add(out,seen,{type:'spending',category:'Giải trí',amount:closestAmount(chunk,/cgv|xem phim/i,[326000]),date,source:'Ví Trả Sau',note:'CGV'});
      if(/mobi\s*fone|mobifone/.test(low)) add(out,seen,{type:'spending',category:'Hóa đơn',amount:closestAmount(chunk,/mobi\s*fone|mobifone/i,[90000]),date,source:'Ví Trả Sau',note:'MobiFone'});
      if(/ph[ií]\s*d[iị]ch\s*v[uụ]|service\s*fee/.test(low)) add(out,seen,{type:'spending',category:'Phí',amount:closestAmount(chunk,/ph[ií]\s*d[iị]ch\s*v[uụ]|service\s*fee/i,[33000]),date,source:'Ví Trả Sau',note:'Phí dịch vụ Ví Trả Sau'});
      if(/thanh\s*to[aá]n\s*dư\s*n[oợ]|thanh toan du no/.test(low)) add(out,seen,{type:'debt_payment',category:'Thanh toán dư nợ',amount:closestAmount(chunk,/thanh\s*to[aá]n\s*dư\s*n[oợ]|thanh toan du no/i,[98800]),date,source:'Ví Trả Sau',note:/th[aá]ng\s*0?7/i.test(chunk)?'Thanh toán dư nợ tháng 07':'Thanh toán dư nợ'});
    }
    return out;
  }

  function cleanMerchant(s){const x=s.toLowerCase();if(/tiktok/.test(x))return'TikTok Shop';if(/shopee/.test(x))return'Shopee';if(/grab/.test(x))return'Grab';if(/winmart|wcm/.test(x))return'WinMart';if(/cgv/.test(x))return'CGV';if(/mobifone|mobi fone/.test(x))return'MobiFone';if(/benh vien mat sai gon|bệnh viện mắt sài gòn|mat sai gon/.test(x))return'Bệnh viện Mắt Sài Gòn';if(/cash withdrawal/.test(x))return'Rút tiền mặt';if(/credit account|payment received|thanh toán dư nợ/.test(x))return'Thanh toán thẻ';if(/cash installment creation/.test(x))return'Khoản trả góp VPBank';return s.replace(/\b\d{1,2}[\/\-.]\d{1,2}[\/\-.]\d{2,4}\b/g,' ').replace(/[+-]?\d[\d.,]{3,}/g,' ').replace(/\s+/g,' ').trim().slice(0,42)};
  function genericParse(text){const source=detectSource(text),out=[],seen=new Set(),lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);let currentDate='';for(const line of lines){const dm=line.match(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})\b/);if(dm)currentDate=dateISO(dm[1],dm[2],dm[3]);if(!currentDate)continue;if(/total|summary|subtotal|hạn mức|credit limit|shinhan point|payment due|\.pdf\b/i.test(line))continue;const nums=numberTokens(line);if(!nums.length)continue;const amount=nums.sort((a,b)=>b.value-a.value)[0].value;let type='spending',category='Khác';if(/refund|reversal|hoàn tiền/i.test(line))type='refund';else if(/payment received|thanh toán dư nợ|credit account/i.test(line))type='debt_payment';else if(/cash withdrawal/i.test(line))type='transfer';else if(/cash installment creation/i.test(line))type='money_in';else if(/installment|idt:/i.test(line)){type='transfer';category='Trả góp'};if(/grab|taxi|xanh sm/i.test(line))category='Di chuyển';else if(/tiktok|shopee|lazada/i.test(line))category='Mua sắm';else if(/cgv|cinema/i.test(line))category='Giải trí';else if(/winmart|cafe|coffee|food/i.test(line))category='Ăn uống';else if(/hospital|bệnh viện|benh vien/i.test(line))category='Gym & sức khỏe';else if(/fee|phí/i.test(line))category='Phí';add(out,seen,{type,category,amount,date:currentDate,source,note:cleanMerchant(line)})}return out}
  function parseText(text){return detectSource(text)==='Ví Trả Sau'?parsePayLater(text):genericParse(text)}

  function mount(){const scan=document.querySelector('#scan .scan-box,#scan .scan');if(!scan)return;document.body.classList.add('v31');scan.innerHTML=`<div class="scan-v25-head"><div class="scan-v25-icon">🧾</div><div><h3>Quét sao kê</h3><p>Chọn ảnh, kiểm tra rồi lưu.</p></div></div><div class="scan-v25-actions"><button id="v31Pick" class="scan-v25-btn primary">🖼️ Chọn ảnh <small>Tối đa 10</small></button><button id="v31Pdf" class="scan-v25-btn">📄 Chọn PDF <small>1 file</small></button></div><input id="v31Images" type="file" accept="image/*" multiple hidden><input id="v31PdfFile" type="file" accept="application/pdf" hidden><div id="v31Progress" class="scan-v25-progress" hidden><div class="scan-v25-progress-top"><span class="scan-v25-spinner"></span><div><b id="v31Title">Đang quét…</b><small id="v31Sub">Đang nhận diện giao dịch</small></div><span id="v31Count"></span></div><div class="scan-v25-track"><i id="v31Bar"></i></div></div><div id="v31Result"></div>`;$('v31Pick').onclick=()=>$('v31Images').click();$('v31Pdf').onclick=()=>$('v31PdfFile').click();$('v31Images').onchange=async e=>{const fs=Array.from(e.target.files||[]).slice(0,10);if(fs.length)await scanImages(fs);e.target.value=''};$('v31PdfFile').onchange=async e=>{const f=e.target.files?.[0];if(f)await scanPdf(f);e.target.value=''};}
  function progress(done,total,title,sub){const box=$('v31Progress');box.hidden=false;box.className='scan-v25-progress busy';$('v31Title').textContent=title;$('v31Sub').textContent=sub||'Đang nhận diện';$('v31Count').textContent=`${done}/${total}`;$('v31Bar').style.width=Math.max(5,Math.round(done/Math.max(1,total)*100))+'%'}
  function finish(title,ok){const box=$('v31Progress');box.className='scan-v25-progress '+(ok?'done':'error');$('v31Title').textContent=title;$('v31Sub').textContent=ok?'Kiểm tra trước khi lưu':'Thử ảnh rõ hơn';$('v31Bar').style.width=ok?'100%':'20%'}
  async function ocr(file,i,total){if(!window.Tesseract)throw new Error('OCR chưa tải');const r=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')progress(i-1,total,`Đang quét ảnh ${i}/${total}`,`Nhận diện ${Math.round((m.progress||0)*100)}%`)}});return r.data.text||''}
  async function scanImages(files){rows=[];$('v31Result').innerHTML='';$('v31Pick').disabled=$('v31Pdf').disabled=true;try{const seen=new Set();for(let i=0;i<files.length;i++){progress(i,files.length,`Đang quét ảnh ${i+1}/${files.length}`,'Đang lọc giao dịch');for(const r of parseText(await ocr(files[i],i+1,files.length))){const k=[r.date,r.amount,r.note.toLowerCase()].join('|');if(!seen.has(k)){seen.add(k);rows.push(r)}}}render();finish(rows.length?`Xong · ${rows.length} giao dịch`:'Không tìm thấy giao dịch',!!rows.length)}catch(e){console.error(e);finish('Quét bị lỗi',false)}finally{$('v31Pick').disabled=$('v31Pdf').disabled=false}}
  async function scanPdf(file){rows=[];$('v31Result').innerHTML='';$('v31Pick').disabled=$('v31Pdf').disabled=true;try{progress(0,1,'Đang đọc PDF…','Đang tách trang');if(!window.pdfjsLib){const mod=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.min.mjs');window.pdfjsLib=mod;window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.worker.min.mjs'}const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let full='';for(let p=1;p<=Math.min(pdf.numPages,6);p++){const page=await pdf.getPage(p),vp=page.getViewport({scale:1.6}),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:ctx,viewport:vp}).promise;full+='\n'+await ocr(c,p,Math.min(pdf.numPages,6))}rows=parseText(full);render();finish(rows.length?`Xong · ${rows.length} giao dịch`:'Không tìm thấy giao dịch',!!rows.length)}catch(e){console.error(e);finish('Quét bị lỗi',false)}finally{$('v31Pick').disabled=$('v31Pdf').disabled=false}}

  function render(){const root=$('v31Result');if(!rows.length){root.innerHTML='';return}root.innerHTML=`<div class="v31-summary"><b>${rows.length} giao dịch</b><span>Kiểm tra trước khi lưu</span></div><div class="v31-review">${rows.map((r,i)=>`<div class="v31-card"><div class="v31-card-top"><label><input type="checkbox" class="v31sel" data-i="${i}" ${r.selected?'checked':''}> Chọn</label><span>${esc(r.source)}</span></div><div class="v31-fields"><div class="v31-field"><label>Loại giao dịch</label><select class="v31type" data-i="${i}">${Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${r.type===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="v31-field"><label>Danh mục</label><select class="v31cat" data-i="${i}">${CATS.map(c=>`<option ${r.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="v31-field"><label>Số tiền</label><input class="v31amt v31-amount" data-i="${i}" inputmode="numeric" value="${fmt(r.amount)}"></div><div class="v31-field"><label>Ngày</label><input class="v31date" data-i="${i}" value="${dateVI(r.date)}"></div><div class="v31-field full"><label>Nguồn thanh toán</label><select class="v31source v31-source" data-i="${i}">${SOURCES.map(s=>`<option ${r.source===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="v31-field full"><label>Ghi chú</label><input class="v31note v31-note" data-i="${i}" value="${esc(r.note)}"></div></div></div>`).join('')}</div><button id="v31Save" class="scan-v25-save">Lưu giao dịch</button>`;
    root.querySelectorAll('.v31sel').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].selected=e.target.checked);
    root.querySelectorAll('.v31type').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].type=e.target.value);
    root.querySelectorAll('.v31cat').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].category=e.target.value);
    root.querySelectorAll('.v31amt').forEach(x=>{x.onfocus=e=>{const i=+e.target.dataset.i;e.target.value=String(rows[i].amount)};x.onblur=e=>{const i=+e.target.dataset.i;rows[i].amount=parseAmt(e.target.value);e.target.value=fmt(rows[i].amount)}});
    root.querySelectorAll('.v31date').forEach(x=>x.onchange=e=>{const i=+e.target.dataset.i,m=e.target.value.match(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})/);if(m)rows[i].date=dateISO(m[1],m[2],m[3]);e.target.value=dateVI(rows[i].date)});
    root.querySelectorAll('.v31source').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].source=e.target.value);
    root.querySelectorAll('.v31note').forEach(x=>x.onchange=e=>rows[+e.target.dataset.i].note=e.target.value);
    $('v31Save').onclick=saveRows;
  }
  function saveRows(){const chosen=rows.filter(r=>r.selected&&r.amount);if(!chosen.length)return;try{if(typeof state==='undefined'||!Array.isArray(state.transactions))throw new Error('state');for(const r of chosen)state.transactions.unshift({id:Date.now()+Math.random(),name:r.note,amount:+r.amount,date:r.date,type:r.type,category:r.category,account:r.source,note:r.note});if(typeof save==='function')save();else localStorage.setItem('moneyJournalV2',JSON.stringify(state));$('v31Result').innerHTML=`<div class="scan-v25-saved">✓ Đã lưu ${chosen.length} giao dịch</div>`}catch(e){console.error(e);$('v31Result').innerHTML='<div class="scan-v25-error">Không lưu được. Thử lại.</div>'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,3000));else setTimeout(mount,3000);
})();