(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const fmt=n=>(Number(n)||0).toLocaleString('vi-VN');
  const norm=t=>{const x=String(t?.type||'');if(x==='debt_payment')return'debt';if(x==='money_in')return'moneyin';return x};
  const typeLabel=t=>({spending:'Chi tiêu',income:'Thu nhập',moneyin:'Tiền nhận',debt:'Trả thẻ',refund:'Hoàn tiền',transfer:'Chuyển tiền'}[norm(t)]||'Khác');
  const months=()=> typeof state==='undefined'?[]:[...new Set((state.transactions||[]).map(t=>String(t.date||'').slice(0,7)).filter(x=>/^\d{4}-\d{2}$/.test(x)))].sort().reverse();
  const monthLabel=ym=>{if(!ym)return'Tất cả';const [y,m]=ym.split('-');return `Tháng ${Number(m)}/${y}`};
  let activeMonth=months()[0]||'';
  let txFilter='all';
  let txQuery='';
  let editingId=null;

  function saveAll(){try{if(typeof save==='function')save();else localStorage.setItem('money_journal_v2_state',JSON.stringify(state));}catch(e){} try{if(typeof renderAll==='function')renderAll()}catch(e){} renderEverything();}
  function monthTx(){return (state?.transactions||[]).filter(t=>!activeMonth||String(t.date||'').startsWith(activeMonth));}
  function sums(){const tx=monthTx();const sum=tp=>tx.filter(t=>norm(t)===tp).reduce((s,t)=>s+(+t.amount||0),0);return{income:sum('income'),moneyin:sum('moneyin'),spending:sum('spending'),debt:sum('debt'),refund:sum('refund')}}
  function spendCats(){const m=new Map();monthTx().filter(t=>norm(t)==='spending').forEach(t=>{const c=String(t.category||'Khác')||'Khác';m.set(c,(m.get(c)||0)+(+t.amount||0))});const rows=[...m].map(([category,amount])=>({category,amount})).sort((a,b)=>b.amount-a.amount);return{rows,total:rows.reduce((s,r)=>s+r.amount,0)}}
  function ledgerRows(){return [...(state?.transactions||[])].filter(t=>(!activeMonth||String(t.date||'').startsWith(activeMonth))&&(txFilter==='all'||norm(t)===txFilter)&&(!txQuery||`${t.name||''} ${t.note||''} ${t.category||''} ${t.source||t.account||''}`.toLowerCase().includes(txQuery.toLowerCase()))).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function buildCashflow(){
    const root=$('#activity');if(!root)return;let screen=root.querySelector('.r43-screen');if(!screen){screen=document.createElement('div');screen.className='r43-screen';root.append(screen)}
    const s=sums(),net=s.income+s.moneyin+s.refund-s.spending-s.debt,{rows,total}=spendCats(),max=rows[0]?.amount||1;
    screen.innerHTML=`<div class="r43-head"><div><small>Dòng tiền</small><h1>Tiền đi đâu?</h1></div><select class="r43-period" id="r43Month">${['',...months()].map(m=>`<option value="${m}" ${m===activeMonth?'selected':''}>${m?monthLabel(m):'Tất cả'}</option>`).join('')}</select></div>
    <section class="r43-card r43-flowHero"><div class="r43-flowTop"><span>Còn lại trong kỳ</span><strong>${fmt(net)}đ</strong></div><div class="r43-flowGrid"><div class="r43-flowMetric"><span>Thu nhập</span><b>${fmt(s.income+s.moneyin)}đ</b></div><div class="r43-flowMetric"><span>Chi tiêu</span><b>${fmt(s.spending)}đ</b></div><div class="r43-flowMetric"><span>Trả thẻ</span><b>${fmt(s.debt)}đ</b></div></div></section>
    <div class="r43-section"><h2>Chi theo danh mục</h2><span>${rows.length} danh mục</span></div><section class="r43-card"><div class="r43-catList">${rows.slice(0,7).map(r=>{const p=total?Math.round(r.amount/total*100):0;return `<div class="r43-cat"><div class="r43-catTop"><b>${esc(r.category)}</b><span>${fmt(r.amount)}đ</span></div><div class="r43-catMeta"><span>${p}% tổng chi</span><span></span></div><div class="r43-track"><i style="width:${Math.max(4,Math.round(r.amount/max*100))}%"></i></div></div>`}).join('')||'<div class="r43-empty">Chưa có chi tiêu trong kỳ này.</div>'}</div></section>
    <div class="r43-section"><h2>Giao dịch</h2><span>${ledgerRows().length} dòng</span></div><div class="r43-tools"><input class="r43-search" id="r43Search" placeholder="Tìm giao dịch"><select class="r43-filter" id="r43Filter"><option value="all">Tất cả</option><option value="spending">Chi tiêu</option><option value="income">Thu nhập</option><option value="moneyin">Tiền nhận</option><option value="debt">Trả thẻ</option><option value="transfer">Chuyển tiền</option></select></div><section class="r43-card r43-ledger" id="r43Ledger"></section>`;
    $('#r43Month').onchange=e=>{activeMonth=e.target.value;buildCashflow()};$('#r43Search').value=txQuery;$('#r43Search').oninput=e=>{txQuery=e.target.value;renderLedger()};$('#r43Filter').value=txFilter;$('#r43Filter').onchange=e=>{txFilter=e.target.value;renderLedger()};renderLedger();
  }
  function renderLedger(){const root=$('#r43Ledger');if(!root)return;const rows=ledgerRows();root.innerHTML=rows.length?rows.map(t=>`<button class="r43-tx" data-id="${esc(t.id)}"><span><strong>${esc(t.note||t.name||'Giao dịch')}</strong><small>${esc(typeLabel(t))} · ${esc(t.category||'Khác')} · ${esc(t.source||t.account||'')}</small></span><span class="r43-txAmt"><b>${fmt(t.amount)}đ</b><small>${String(t.date||'').split('-').reverse().join('/')}</small></span></button>`).join(''):'<div class="r43-empty">Không có giao dịch phù hợp.</div>';root.querySelectorAll('.r43-tx').forEach(b=>b.onclick=()=>openEdit(b.dataset.id));}
  function buildPlan(){
    const root=$('#budget');if(!root)return;let screen=root.querySelector('.r43-screen');if(!screen){screen=document.createElement('div');screen.className='r43-screen';root.append(screen)}
    const budgets=state?.budgets||[],tx=monthTx().filter(t=>norm(t)==='spending');const spentBy=c=>tx.filter(t=>String(t.category||'')===c).reduce((s,t)=>s+(+t.amount||0),0);const totalLimit=budgets.reduce((s,b)=>s+(+b.limit||0),0),totalSpent=budgets.reduce((s,b)=>s+spentBy(b.name),0),pct=totalLimit?Math.min(100,Math.round(totalSpent/totalLimit*100)):0;const g=state?.goal||{};const gp=g.target?Math.min(100,Math.round((+g.saved||0)/(+g.target||1)*100)):0;
    screen.innerHTML=`<div class="r43-head"><div><small>Kế hoạch</small><h1>Giữ đúng nhịp</h1></div><select class="r43-period" id="r43PlanMonth">${['',...months()].map(m=>`<option value="${m}" ${m===activeMonth?'selected':''}>${m?monthLabel(m):'Tất cả'}</option>`).join('')}</select></div><section class="r43-card"><small style="color:var(--r43-muted);font-size:10px;font-weight:800">Ngân sách đã dùng</small><div class="r43-budgetBig">${fmt(totalSpent)}đ</div><div class="r43-budgetSub"><span>${pct}% ngân sách</span><span>${fmt(totalLimit)}đ giới hạn</span></div><div class="r43-track" style="margin-top:10px"><i style="width:${pct}%"></i></div></section><div class="r43-section"><h2>Danh mục</h2><button class="r43-textbtn" onclick="document.querySelector('.nav[data-tab=activity]')?.click()">Xem giao dịch</button></div><section class="r43-card">${budgets.map(b=>{const sp=spentBy(b.name),p=b.limit?Math.min(100,Math.round(sp/b.limit*100)):0;return `<div class="r43-budgetRow"><div class="r43-budgetRowTop"><b>${esc(b.name)}</b><span>${fmt(sp)} / ${fmt(b.limit)}đ</span></div><div class="r43-track" style="margin-top:8px"><i style="width:${p}%"></i></div></div>`}).join('')||'<div class="r43-empty">Chưa có ngân sách.</div>'}</section><div class="r43-section"><h2>Mục tiêu tiết kiệm</h2><button class="r43-textbtn" id="r43EditGoal">Chỉnh sửa</button></div><section class="r43-card r43-goal"><div><strong>${esc(g.name||'Quỹ mục tiêu')}</strong><small>${fmt(g.saved||0)}đ / ${fmt(g.target||0)}đ</small></div><div class="r43-goalPct" style="--pct:${gp}%"><span>${gp}%</span></div></section>`;
    $('#r43PlanMonth').onchange=e=>{activeMonth=e.target.value;buildPlan()};$('#r43EditGoal').onclick=()=>{const n=prompt('Tên mục tiêu',g.name||'Quỹ mục tiêu');if(n===null)return;const t=Number(prompt('Mục tiêu (VND)',g.target||0));const sv=Number(prompt('Đã để dành (VND)',g.saved||0));state.goal={name:n,target:t||0,saved:sv||0};saveAll()};
  }
  function buildSettings(){
    const root=$('#profile');if(!root)return;let screen=root.querySelector('.r43-screen');if(!screen){screen=document.createElement('div');screen.className='r43-screen';root.append(screen)}const dark=document.documentElement.getAttribute('data-theme')==='dark';
    screen.innerHTML=`<div class="r43-head"><div><small>Cài đặt</small><h1>Ứng dụng của bạn</h1></div></div><section class="r43-card r43-settings"><div class="r43-setting"><span><b>Chế độ tối</b><small>Giữ nguyên lựa chọn lần sau</small></span><button id="r43Theme" class="r43-switch ${dark?'on':''}" aria-label="Dark mode"><i></i></button></div><div class="r43-setting"><span><b>Xuất bản sao lưu</b><small>Lưu toàn bộ dữ liệu thành JSON</small></span><button class="r43-btn" id="r43Export">Xuất</button></div><div class="r43-setting"><span><b>Khôi phục dữ liệu</b><small>Nhập file backup đã lưu</small></span><button class="r43-btn" id="r43Import">Nhập</button></div><div class="r43-setting"><span><b>Xóa dữ liệu cục bộ</b><small>Không thể hoàn tác nếu chưa backup</small></span><button class="r43-btn danger" id="r43Reset">Xóa</button></div></section><div class="r43-section"><h2>Lưu trữ</h2></div><section class="r43-card"><div style="font-size:12px;line-height:1.6;color:var(--r43-muted)">Dữ liệu hiện lưu trực tiếp trên thiết bị này bằng localStorage. Không tự đồng bộ lên server.</div></section>`;
    $('#r43Theme').onclick=()=>document.querySelector('.mj-theme-toggle')?.click();$('#r43Export').onclick=()=>typeof exportBackup==='function'&&exportBackup();$('#r43Import').onclick=()=>document.getElementById('restore')?.click();$('#r43Reset').onclick=()=>typeof resetData==='function'&&resetData();
  }
  function ensureModals(){if($('#r43ActionModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="r43-modal" id="r43ActionModal"><div class="r43-sheet"><div class="r43-sheetHead"><h3>Thêm mới</h3><button class="r43-close" data-close>×</button></div><div class="r43-actions"><button class="r43-action" id="r43Manual"><b>Giao dịch thủ công</b><small>Nhập nhanh một khoản thu, chi, trả thẻ hoặc chuyển tiền.</small></button><button class="r43-action" id="r43Scan"><b>Quét sao kê</b><small>Đọc ảnh/PDF và kiểm tra trước khi lưu.</small></button></div></div></div><div class="r43-modal" id="r43EditModal"><div class="r43-sheet"><div class="r43-sheetHead"><h3>Chỉnh giao dịch</h3><button class="r43-close" data-close>×</button></div><div class="r43-editGrid"><div class="r43-field"><label>Loại</label><select id="r43EType"><option value="spending">Chi tiêu</option><option value="income">Thu nhập</option><option value="moneyin">Tiền nhận</option><option value="debt">Trả thẻ</option><option value="refund">Hoàn tiền</option><option value="transfer">Chuyển tiền</option></select></div><div class="r43-field"><label>Danh mục</label><input id="r43ECat"></div><div class="r43-field"><label>Số tiền</label><input id="r43EAmount" inputmode="numeric"></div><div class="r43-field"><label>Ngày</label><input id="r43EDate" type="date"></div><div class="r43-field full"><label>Nguồn</label><input id="r43ESource"></div><div class="r43-field full"><label>Ghi chú</label><input id="r43ENote"></div></div><button class="r43-save" id="r43Save">Lưu thay đổi</button><button class="r43-delete" id="r43Delete">Xóa giao dịch</button></div></div>`);$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.r43-modal').classList.remove('show'));$('#r43ActionModal').onclick=e=>{if(e.target.id==='r43ActionModal')e.currentTarget.classList.remove('show')};$('#r43EditModal').onclick=e=>{if(e.target.id==='r43EditModal')e.currentTarget.classList.remove('show')};$('#r43Manual').onclick=()=>{$('#r43ActionModal').classList.remove('show');if(typeof openAdd==='function')openAdd()};$('#r43Scan').onclick=()=>{$('#r43ActionModal').classList.remove('show');switchTab('scan')};$('#r43Save').onclick=saveEdit;$('#r43Delete').onclick=deleteEdit;}
  function openEdit(id){ensureModals();const t=(state.transactions||[]).find(x=>String(x.id)===String(id));if(!t)return;editingId=id;$('#r43EType').value=norm(t);$('#r43ECat').value=t.category||'Khác';$('#r43EAmount').value=fmt(t.amount);$('#r43EDate').value=t.date||'';$('#r43ESource').value=t.source||t.account||'';$('#r43ENote').value=t.note||t.name||'';$('#r43EditModal').classList.add('show')}
  function saveEdit(){const t=(state.transactions||[]).find(x=>String(x.id)===String(editingId));if(!t)return;t.type=$('#r43EType').value;t.category=$('#r43ECat').value.trim()||'Khác';t.amount=Number(String($('#r43EAmount').value).replace(/[^\d]/g,''))||0;t.date=$('#r43EDate').value;t.source=$('#r43ESource').value.trim();t.account=t.source;t.note=$('#r43ENote').value.trim();t.name=t.note||t.name||'Giao dịch';$('#r43EditModal').classList.remove('show');saveAll()}
  function deleteEdit(){if(!editingId)return;state.transactions=state.transactions.filter(t=>String(t.id)!==String(editingId));$('#r43EditModal').classList.remove('show');saveAll()}
  function switchTab(tab){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===tab));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));if(tab==='activity')buildCashflow();if(tab==='budget')buildPlan();if(tab==='profile')buildSettings();}
  function nav(){const labels={home:'Tổng quan',activity:'Dòng tiền',budget:'Kế hoạch',profile:'Cài đặt'};$$('.nav').forEach(b=>{const tab=b.dataset.tab;if(tab==='scan'){b.innerHTML='<span class="fab">＋</span>';b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();ensureModals();$('#r43ActionModal').classList.add('show')};return}b.innerHTML=`<small>${labels[tab]||''}</small>`;b.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();switchTab(tab)}})}
  function renderEverything(){buildCashflow();buildPlan();buildSettings()}
  function boot(){ensureModals();nav();renderEverything();setTimeout(()=>{nav();renderEverything()},1200);setTimeout(()=>{nav();renderEverything()},5200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,6200));else setTimeout(boot,6200);
})();