(() => {
  const KEY='money_journal_v2_state', THEME='mj_theme_mode';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>(Number(n)||0).toLocaleString('vi-VN');
  const today=()=>new Date().toISOString().slice(0,10);
  const normalizeType=x=>x==='money_in'?'moneyin':x==='debt_payment'?'debt':x;
  const TYPES=[['spending','Chi tiêu'],['income','Thu nhập'],['moneyin','Tiền nhận'],['debt','Trả thẻ'],['refund','Hoàn tiền'],['transfer','Chuyển tiền']];
  const CATS=['Ăn uống','Di chuyển','Mua sắm','Hẹn hò','Giải trí','Hóa đơn','Sức khỏe','Làm đẹp','Dịch vụ số','Quà tặng','Phí','Trả góp','Thanh toán dư nợ','Tiết kiệm','Lương','Khác'];
  const SOURCES=['Tiền mặt','VPBank','Shinhan','Ví Trả Sau','Tài khoản ngân hàng','Tiết kiệm','Khác'];
  let page='home', selectedMonth=null, filter='all', query='', editing=null;
  function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');if(!Array.isArray(s.transactions))s.transactions=[];if(!Array.isArray(s.accounts))s.accounts=[];if(!Array.isArray(s.budgets))s.budgets=[];return s}catch{return{transactions:[],accounts:[],budgets:[]}}}
  function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
  function months(){return [...new Set(load().transactions.map(t=>String(t.date||'').slice(0,7)).filter(x=>/^\d{4}-\d{2}$/.test(x)))].sort().reverse()}
  function currentMonth(){const ms=months();return selectedMonth&&ms.includes(selectedMonth)?selectedMonth:(ms[0]||new Date().toISOString().slice(0,7))}
  function monthLabel(ym){if(!ym)return'';const [y,m]=ym.split('-');return `Tháng ${Number(m)}/${y}`}
  function typeOf(t){return normalizeType(String(t.type||''))}
  function sum(a,t){return a.filter(x=>typeOf(x)===t).reduce((s,x)=>s+(+x.amount||0),0)}
  function calc(ym=currentMonth()){
    const s=load(), all=s.transactions, month=all.filter(t=>String(t.date||'').startsWith(ym));
    const income=sum(month,'income'), moneyin=sum(month,'moneyin'), spend=sum(month,'spending'), debt=sum(month,'debt'), refund=sum(month,'refund');
    const left=income+moneyin-spend-debt+refund;
    const getBal=n=>s.accounts.find(a=>String(a.name||'').toLowerCase()===n.toLowerCase())?.balance||0;
    return {s,all,month,ym,income,moneyin,spend,debt,refund,left,cash:getBal('Tiền mặt'),savings:getBal('Tiết kiệm')}
  }
  function txName(t){return t.note||t.name||'Giao dịch'}
  function txRows(list,limit){const a=[...list].sort((x,y)=>String(y.date||'').localeCompare(String(x.date||'')));const rows=(limit?a.slice(0,limit):a);return rows.map(t=>`<button class="tx" data-edit="${esc(t.id)}"><span><b>${esc(txName(t))}</b><small>${esc(t.category||'Khác')}${t.source||t.account?' · '+esc(t.source||t.account):''}</small></span><span class="right"><b>${fmt(t.amount)}đ</b><small>${String(t.date||'').split('-').reverse().join('/')}</small></span><span class="chev">›</span></button>`).join('')||'<div class="empty">Chưa có giao dịch.</div>'}
  function catStats(list){const m=new Map();list.filter(t=>typeOf(t)==='spending').forEach(t=>m.set(t.category||'Khác',(m.get(t.category||'Khác')||0)+(+t.amount||0)));const rows=[...m].map(([category,amount])=>({category,amount})).sort((a,b)=>b.amount-a.amount);return {rows,total:rows.reduce((s,r)=>s+r.amount,0),max:rows[0]?.amount||1}}
  function renderHome(){const c=calc();return `<section class="hero"><small>Tiền còn lại · ${monthLabel(c.ym)}</small><div class="balance">${fmt(c.left)}đ</div><div class="hero-note">Sau thu nhập, chi tiêu và trả thẻ</div><div class="hero-grid"><div><span>Thu nhập</span><b>${fmt(c.income)}đ</b></div><div><span>Chi tiêu</span><b>${fmt(c.spend)}đ</b></div><div><span>Trả thẻ</span><b>${fmt(c.debt)}đ</b></div></div></section><div class="section-head"><h2>Tài khoản</h2><button data-page="settings">Quản lý</button></div><div class="grid2"><div class="mini"><small>Tiền mặt</small><b>${fmt(c.cash)}đ</b></div><div class="mini"><small>Tiết kiệm</small><b>${fmt(c.savings)}đ</b></div></div><div class="section-head"><h2>Gần đây</h2><button data-page="flow">Xem tất cả</button></div><div class="card">${txRows(c.all,5)}</div>`}
  function renderFlow(){const c=calc(), ms=months(), st=catStats(c.month);let list=c.month;if(filter!=='all')list=list.filter(t=>typeOf(t)===filter);if(query)list=list.filter(t=>`${txName(t)} ${t.category||''} ${t.source||t.account||''}`.toLowerCase().includes(query.toLowerCase()));return `<div class="title-row"><div><div class="eyebrow">Dòng tiền</div><h1>${monthLabel(c.ym)}</h1></div><select id="monthSelect" class="month-select">${ms.map(m=>`<option value="${m}" ${m===c.ym?'selected':''}>${monthLabel(m)}</option>`).join('')||`<option value="${c.ym}">${monthLabel(c.ym)}</option>`}</select></div><div class="summary"><div class="metric primary"><small>Còn lại</small><b>${fmt(c.left)}đ</b></div><div class="metric"><small>Đã chi</small><b>${fmt(c.spend)}đ</b></div><div class="metric"><small>Trả thẻ</small><b>${fmt(c.debt)}đ</b></div></div><div class="section-head"><h2>Chi theo danh mục</h2></div><div class="card">${st.rows.length?st.rows.slice(0,8).map(r=>{const p=st.total?Math.round(r.amount/st.total*100):0,w=Math.max(5,Math.round(r.amount/st.max*100));return `<div class="cat-row"><div><div class="cat-label"><b>${esc(r.category)}</b><span>${p}%</span></div><div class="bar"><i style="width:${w}%"></i></div></div><div class="cat-amt">${fmt(r.amount)}đ</div></div>`}).join(''):'<div class="empty">Chưa có chi tiêu trong tháng này.</div>'}</div><div class="section-head"><h2>Giao dịch</h2></div><div class="filters">${[['all','Tất cả'],['spending','Chi tiêu'],['debt','Trả thẻ'],['income','Thu nhập'],['moneyin','Tiền nhận'],['transfer','Chuyển tiền']].map(([k,v])=>`<button class="pill ${filter===k?'active':''}" data-filter="${k}">${v}</button>`).join('')}</div><input id="search" class="search" value="${esc(query)}" placeholder="Tìm giao dịch"><div class="card">${txRows(list)}</div>`}
  function renderPlan(){const c=calc(), b=c.s.budgets||[], spendMap=new Map();c.month.filter(t=>typeOf(t)==='spending').forEach(t=>spendMap.set(t.category||'Khác',(spendMap.get(t.category||'Khác')||0)+(+t.amount||0)));const limit=b.reduce((s,x)=>s+(+x.limit||0),0), remain=limit-c.spend, used=limit?Math.round(c.spend/limit*100):0, g=c.s.goal||{name:'Mục tiêu tiết kiệm',target:0,saved:c.savings}, gp=g.target?Math.min(100,Math.round((+g.saved||0)/(+g.target||1)*100)):0;return `<div class="title-row"><div><div class="eyebrow">Kế hoạch</div><h1>${monthLabel(c.ym)}</h1></div></div><div class="card plan-hero"><small>Còn trong ngân sách</small><b>${fmt(remain)}đ</b><div class="bar" style="background:#ffffff55;margin-top:14px"><i style="width:${Math.min(100,used)}%;background:#241a0d"></i></div></div><div class="section-head"><h2>Ngân sách</h2></div><div class="card">${b.length?b.map(x=>{const u=spendMap.get(x.name)||0,p=x.limit?Math.min(100,Math.round(u/x.limit*100)):0;return `<div class="budget-row"><div class="budget-line"><b>${esc(x.name)}</b><span>${fmt(u)}đ / ${fmt(x.limit)}đ</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join(''):'<div class="empty">Chưa có ngân sách.</div>'}</div><div class="section-head"><h2>Mục tiêu tiết kiệm</h2></div><div class="card"><div class="budget-line"><b>${esc(g.name||'Mục tiêu tiết kiệm')}</b><span>${gp}%</span></div><div style="font-size:25px;font-weight:900;letter-spacing:-.04em;margin-top:8px">${fmt(g.saved||c.savings)}đ</div><div class="bar"><i style="width:${gp}%"></i></div></div>`}
  function renderSettings(){const c=calc(), dark=localStorage.getItem(THEME)==='dark';return `<div class="title-row"><div><div class="eyebrow">Cài đặt</div><h1>Money Journal</h1></div></div><div class="card"><div class="setting"><div><b>Giao diện</b><small>${dark?'Tối':'Sáng'}</small></div><button id="themeInline">${dark?'Chuyển sáng':'Chuyển tối'}</button></div><div class="setting"><div><b>Số dư</b><small>Tiền mặt ${fmt(c.cash)}đ · Tiết kiệm ${fmt(c.savings)}đ</small></div><button id="editBalances">Chỉnh</button></div></div><div class="section-head"><h2>Dữ liệu</h2></div><div class="card"><div class="setting"><div><b>Sao lưu</b><small>Xuất JSON</small></div><button id="exportBtn">Xuất</button></div><div class="setting"><div><b>Khôi phục</b><small>Nhập file JSON</small></div><button id="importBtn">Nhập</button></div><div class="setting"><div><b>Xóa dữ liệu</b><small>Nên sao lưu trước</small></div><button class="danger" id="resetBtn">Xóa</button></div></div><input id="importFile" hidden type="file" accept="application/json">`}
  function render(){const root=$('#screen');root.innerHTML=page==='home'?renderHome():page==='flow'?renderFlow():page==='plan'?renderPlan():renderSettings();bindPage();$$('.nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
  function bindPage(){$$('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();scrollTo({top:0,behavior:'smooth'})});$$('[data-edit]').forEach(b=>b.onclick=()=>openTx(b.dataset.edit));$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});$('#monthSelect')?.addEventListener('change',e=>{selectedMonth=e.target.value;render()});$('#search')?.addEventListener('input',e=>{query=e.target.value;render()});$('#themeInline')?.addEventListener('click',toggleTheme);$('#editBalances')?.addEventListener('click',openBalances);$('#exportBtn')?.addEventListener('click',exportData);$('#importBtn')?.addEventListener('click',()=>$('#importFile').click());$('#importFile')?.addEventListener('change',e=>importData(e.target.files[0]));$('#resetBtn')?.addEventListener('click',()=>{if(confirm('Xóa toàn bộ dữ liệu trên thiết bị này?')){localStorage.removeItem(KEY);render()}})}
  function showSheet(html){const o=$('#overlay');o.innerHTML=`<div class="sheet"><div class="handle"></div>${html}</div>`;o.classList.add('show');o.onclick=e=>{if(e.target===o)closeSheet()}}
  function closeSheet(){$('#overlay').classList.remove('show');$('#overlay').innerHTML=''}
  function openAdd(){showSheet(`<h2>Thêm</h2><p>Chọn một cách.</p><button class="choice" id="manual"><b>Giao dịch</b><small>Nhập và lưu ngay.</small></button><button class="choice" id="statement"><b>Sao kê</b><small>Quét sao kê đang ở chế độ thử nghiệm.</small></button>`);$('#manual').onclick=()=>openTx(null);$('#statement').onclick=()=>{alert('Phần quét sao kê đang được tách riêng để tránh làm chậm giao diện. Mình sẽ nối lại parser sau khi chốt UI V5.');}}
  function openTx(id){editing=id;const t=id?load().transactions.find(x=>String(x.id)===String(id)):null;showSheet(`<h2>${t?'Sửa giao dịch':'Giao dịch mới'}</h2><p>${t?'Chỉnh rồi lưu lại.':'Nhập các thông tin cần thiết.'}</p><div class="form"><label>Loại<select id="fType">${TYPES.map(([v,l])=>`<option value="${v}" ${normalizeType(t?.type)===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Số tiền<input id="fAmount" type="number" inputmode="numeric" value="${t?.amount||''}"></label><label>Ngày<input id="fDate" type="date" value="${t?.date||today()}"></label><label>Danh mục<select id="fCat">${CATS.map(v=>`<option ${t?.category===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="full">Nguồn<select id="fSource">${SOURCES.map(v=>`<option ${String(t?.source||t?.account||'')===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="full">Ghi chú<input id="fNote" value="${esc(t?.note||t?.name||'')}"></label></div><div class="actions">${t?'<button class="btn-secondary danger" id="deleteTx">Xóa</button>':''}<button class="btn-secondary" id="cancelTx">Hủy</button><button class="btn-primary" id="saveTx">Lưu</button></div>`);$('#cancelTx').onclick=closeSheet;$('#saveTx').onclick=saveTx;if(t)$('#deleteTx').onclick=()=>{const s=load();s.transactions=s.transactions.filter(x=>String(x.id)!==String(id));save(s);closeSheet();render()}}
  function saveTx(){const amount=Number($('#fAmount').value);if(!amount){alert('Nhập số tiền trước nha.');return}const s=load();const obj={id:editing||`tx_${Date.now()}`,type:$('#fType').value,amount,date:$('#fDate').value,category:$('#fCat').value,source:$('#fSource').value,note:$('#fNote').value.trim()};if(editing){const i=s.transactions.findIndex(x=>String(x.id)===String(editing));if(i>=0)s.transactions[i]={...s.transactions[i],...obj}}else s.transactions.push(obj);save(s);closeSheet();render()}
  function openBalances(){const c=calc();showSheet(`<h2>Số dư</h2><p>Đây là số dư hiện tại, không phải giao dịch.</p><div class="form"><label>Tiền mặt<input id="cashBal" type="number" value="${c.cash}"></label><label>Tiết kiệm<input id="saveBal" type="number" value="${c.savings}"></label></div><div class="actions"><button class="btn-secondary" id="cancelBal">Hủy</button><button class="btn-primary" id="saveBalBtn">Lưu</button></div>`);$('#cancelBal').onclick=closeSheet;$('#saveBalBtn').onclick=()=>{const s=load();const up=(n,v)=>{let a=s.accounts.find(x=>String(x.name||'').toLowerCase()===n.toLowerCase());if(a)a.balance=Number(v)||0;else s.accounts.push({id:`acc_${Date.now()}_${n}`,name:n,balance:Number(v)||0})};up('Tiền mặt',$('#cashBal').value);up('Tiết kiệm',$('#saveBal').value);save(s);closeSheet();render()}}
  function toggleTheme(){const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.setItem(THEME,d?'light':'dark');render();$('#themeBtn').textContent=d?'◐':'☀︎'}
  function exportData(){const blob=new Blob([JSON.stringify(load(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`money-journal-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
  async function importData(file){if(!file)return;try{const data=JSON.parse(await file.text());save(data);render();alert('Đã khôi phục dữ liệu.')}catch{alert('File backup không hợp lệ.')}}
  function boot(){const theme=localStorage.getItem(THEME)==='dark'?'dark':'light';document.documentElement.dataset.theme=theme;$('#themeBtn').textContent=theme==='dark'?'☀︎':'◐';$('#themeBtn').onclick=toggleTheme;$('#addBtn').onclick=openAdd;$$('.nav [data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();scrollTo({top:0,behavior:'smooth'})});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();